package com.datacompanies.beans;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

public class AnnualAccount {

	   private String SIREN;

	    //-------------------------------------------------------
	    //int :
	    
	    private int ACTIF;

	    private int CAPITAL_SOUSCRIT_NON_APPELE;

	    private int FRAIS_D_ETABLISSEMENT;

	    private int FRAIS_DE_DEVELOPPEMENT_OU_DE_RECHERCHE_ET_DEVELOPPEMENT;

	    private int CONCESSIONS_BREVETS_ET_DROITS_SIMILAIRES;

	    private int FONDS_COMMERCIAL;

	    private int AUTRES_IMMOBILISATIONS_INCORPORELLES;

	    private int AVANCES_ET_ACOMPTES_SUR_IMMOBILISATIONS_INCORPORELLES;

	    private int TERRAINS;

	    private int CONSTRUCTIONS;

	    private int INSTALLATIONS_TECHNIQUES_MATERIEL_ET_OUTILLAGE_INDUSTRIELS;

	    private int AUTRES_IMMOBILISATIONS_CORPORELLES;

	    private int IMMOBILISATIONS_EN_COURS;

	    private int AVANCES_ET_ACOMPTES;

	    private int PARTICIPATIONS_EVALUEES_MISE_EN_EQUIVALENCE;

	    private int AUTRES_PARTICIPATIONS;

	    private int CREANCES_RATTACHEES_A_DES_PARTICIPATIONS;

	    private int AUTRES_TITRES_IMMOBILISES;

	    private int PRETS;

	    private int AUTRES_IMMOBILISATIONS_FINANCIERES;

	    private int TOTAL_I;

	    private int MATIERES_PREMIERES_APPROVISIONNEMENTS;

	    private int EN_COURS_DE_PRODUCTION_DE_BIENS;

	    private int EN_COURS_DE_PRODUCTION_DE_SERVICES;

	    private int PRODUITS_INTERMEDIAIRES_ET_FINIS;

	    private int MARCHANDISES;

	    private int AVANCES_ET_ACOMPTES_VERSES_SUR_COMMANDES;

	    private int CLIENTS_ET_COMPTES_RATTACHES;

	    private int AUTRES_CREANCES;

	    private int CAPITAL_SOUSCRIT_ET_APPELE_NON_VERSE;

	    private int VALEURS_MOBILIERES_DE_PLACEMENT;

	    private int DISPONIBILITES;

	    private int CHARGES_CONSTATEES_D_AVANCE;

	    private int TOTAL_II;

	    private int CHARGES_A_REPARTIR_OU_FRAIS_D_EMISSION_D_EMPRUNT;

	    private int PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS_IV;

	    private int ECARTS_DE_CONVERSION_ACTIF_V;

	    private int TOTAL_GENERAL_0_A_V;

	    private int PARTS_A_MOINS_D_UN_AN;

	    private int PARTS_A_PLUS_D_UN_AN;

	    private int PASSIF;

	    private int CAPITAL_SOCIAL_OU_INDIVIDUEL;

	    private int PRIMES_D_EMISSION_DE_FUSION_D_APPORT;

	    private int DONT_ECART_D_EQUIVALENCE;

	    private int ECARTS_DE_REEVALUATION;

	    private int RESERVE_LEGALE_1;

	    private int RESERVES_STATUTAIRES_OU_CONTRACTUELLES;

	    private int DONT_RESERVE_SPECIALE_DES_PROVISIONS_POUR_FLUCTUATION_DES_COURS;

	    private int RESERVES_REGLEMENTEES_1;

	    private int DONT_RESERVE_RELATIVE_A_L_ACHAT_D_OEUVRES_ORIGINALES_D_ARTISTES_VIVANTS;

	    private int AUTRES_RESERVES;

	    private int REPORT_A_NOUVEAU;

	    private int RESULTAT_DE_L_EXERCICE_BENEFICE_OU_PERTE;

	    private int SUBVENTIONS_D_INVESTISSEMENT;

	    private int PROVISIONS_REGLEMENTEES;

	    private int PRODUIT_DES_EMISSIONS_DE_TITRES_PARTICIPATIFS;

	    private int AVANCES_CONDITIONNEES;

	    private int PROVISIONS_POUR_RISQUES;

	    private int PROVISIONS_POUR_CHARGES;

	    private int TOTAL_III;

	    private int EMPRUNTS_OBLIGATAIRES_CONVERTIBLES;

	    private int AUTRES_EMPRUNTS_OBLIGATAIRES;

	    private int EMPRUNTS_ET_DETTES_AUPRES_DES_ETABLISSEMENTS_DE_CREDIT_3;

	    private int EMPRUNTS_ET_DETTES_FINANCIERES_DIVERS_4;

	    private int AVANCES_ET_ACOMPTES_RECUS_SUR_COMMANDES_EN_COURS;

	    private int DETTES_FOURNISSEURS_ET_COMPTES_RATTACHES;

	    private int DETTES_FISCALES_ET_SOCIALES;

	    private int DETTES_SUR_IMMOBILISATIONS_ET_COMPTES_RATTACHES;

	    private int AUTRES_DETTES;

	    private int PRODUITS_CONSTATES_D_AVANCE_2;

	    private int TOTAL_IV;

	    private int V;

	    private int TOTAL_GENERAL_I_A_V;

	    private int DONT_RESERVE_REGLEMENTEE_DES_PLUSVALUES_A_LONG_TERME;

	    private int DETTES_ET_PRODUITS_CONSTATES_D_AVANCE_A_MOINS_D_UN_AN;

	    private int DONT_CONCOURS_BANCAIRES_COURANTS_ET_SOLDES_CREDITEURS_DE_BANQUES_ET_CCP;

	    private int DONT_EMPRUNTS_PARTICIPATIFS;

	    private int COMPTE_DE_RESULTAT_A;

	    private int VENTES_DE_MARCHANDISES;

	    private int PRODUCTION_VENDUE_BIENS;

	    private int PRODUCTION_VENDUE_SERVICES;

	    private int CHIFFRES_D_AFFAIRES_NETS;

	    private int PRODUCTION_STOCKEE;

	    private int PRODUCTION_IMMOBILISEE;

	    private int SUBVENTIONS_D_EXPLOITATION;

	    private int REPRISES_SUR_AMORTISSEMENTS_ET_PROVISIONS_TRANSFERT_DE_CHARGES;

	    private int AUTRES_PRODUITS;

	    private int TOTAL_DES_PRODUITS_D_EXPLOITATION_I;

	    private int ACHATS_DE_MARCHANDISES_Y_COMPRIS_DROITS_DE_DOUANE;

	    private int VARIATION_DE_STOCK_MARCHANDISES;

	    private int ACHATS_DE_MATIERES_PREMIERES_ET_AUTRES_APPROVISIONNEMENTS;

	    private int VARIATION_DE_STOCK_MATIERES_PREMIERES_ET_APPROVISIONNEMENTS;

	    private int AUTRES_ACHATS_ET_CHARGES_EXTERNES;

	    private int IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES;

	    private int SALAIRES_ET_TRAITEMENTS;

	    private int CHARGES_SOCIALES;

	    private int DOT_D_EXPLOIT_DOTATIONS_AUX_AMORTISSEMENTS;

	    private int DOT_D_EXPLOIT_DOTATIONS_AUX_PROVISIONS;

	    private int DOT_D_EXPLOIT_SUR_ACTIF_CIRCULANT_DOTATIONS_AUX_PROVISIONS;

	    private int DOT_D_EXPLOIT_POUR_RISQUES_ET_CHARGES_DOTATIONS_AUX_PROVISIONS;

	    private int AUTRES_CHARGES;

	    private int TOTAL_DES_CHARGES_D_EXPLOITATION_II;

	    private int RESULTAT_D_EXPLOITATION_I_II;

	    private int BENEFICE_ATTRIBUE_OU_PERTE_TRANSFEREE_III;

	    private int PERTE_SUPPORTEE_OU_BENEFICE_TRANSFERE_IV;

	    private int PRODUITS_FINANCIERS_DE_PARTICIPATIONS;

	    private int PRODUITS_DES_AUTRES_VALEURS_MOBILIERES_ET_CREANCES_DE_L_ACTIF_IMMOBILISE;

	    private int AUTRES_INTERETS_ET_PRODUITS_ASSIMILES;

	    private int REPRISES_SUR_PROVISIONS_ET_TRANSFERTS_DE_CHARGES;

	    private int DIFFERENCES_POSITIVES_DE_CHANGE;

	    private int PRODUITS_NETS_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT;

	    private int TOTAL_DES_PRODUITS_FINANCIERS_V;

	    private int DOTATIONS_FINANCIERES_SUR_AMORTISSEMENTS_ET_PROVISIONS;

	    private int INTERETS_ET_CHARGES_ASSIMILEES;

	    private int DIFFERENCES_NEGATIVES_DE_CHANGE;

	    private int CHARGES_NETTES_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT;

	    private int TOTAL_DES_CHARGES_FINANCIERES_VI;

	    private int RESULTAT_FINANCIER_V_VI;

	    private int RESULTAT_COURANT_AVANT_IMPOTS_I_II_III_IV_V_VI;

	    private int COMPTE_DE_RESULTAT_B;

	    private int PRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_DE_GESTION;

	    private int PRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_EN_CAPITAL;

	    private int TOTAL_DES_PRODUITS_EXCEPTIONNELS_VII;

	    private int CHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_DE_GESTION;

	    private int CHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_EN_CAPITAL;

	    private int DOTATIONS_EXCEPTIONNELLES_AUX_AMORTISSEMENTS_ET_PROVISIONS;

	    private int TOTAL_DES_CHARGES_EXCEPTIONNELLES_VIII;

	    private int RESULTAT_EXCEPTIONNEL_VII_VIII;

	    private int PARTICIPATION_DES_SALARIES_AUX_RESULTATS_DE_L_ENTREPRISE;

	    private int IMPOTS_SUR_LES_BENEFICES_X;

	    private int TOTAL_DES_PRODUITS_I_III_V_VII;

	    private int TOTAL_DES_CHARGES_II_IV_VI_VIII_IX_X;

	    private int BENEFICE_OU_PERTE_TOTAL_DES_PRODUITS_TOTAL_DES_CHARGES;

	    private int RENVOIS_CREDITBAIL_MOBILIER;

	    private int RENVOIS_CREDITBAIL_IMMOBILIER;

	    private int RENVOIS_TRANSFERT_DE_CHARGES;

	    private int RENVOIS_COTISATIONS_PERSONNELLES_DE_L_EXPLOITANT;

	    private int RENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_PRODUITS;

	    private int RENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_CHARGES;

	    private int IMMOBILISATIONS;

	    private int ACQUISITIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;

	    private int ACQUISITIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES;

	    private int ACQUISITIONS_TOTAL_IMMOBILISATIONS_CORPORELLES;

	    private int ACQUISITIONS_TOTAL_IMMOBILISATIONS_FINANCIERES;

	    private int ACQUISITIONS_TOTAL_GENERAL;

	    private int DIMINUTIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;

	    private int DIMINUTIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES;

	    private int DIMINUTIONS_VIREMENT_POSTES_IMMOBILISATIONS_CORPORELLES_EN_COURS;

	    private int DIMINUTIONS_VIREMENT_POSTES_AVANCES_ET_ACOMPTES;

	    private int DIMINUTIONS_TOTAL_IMMOBILISATIONS_CORPORELLES;

	    private int DIMINUTIONS_PRETS_ET_IMMOBILISATIONS_FINANCIERES;

	    private int DIMINUTIONS_TOTAL_IMMOBILISATIONS_FINANCIERES;

	    private int DIMINUTIONS_TOTAL_GENERAL;

	    private int AMORTISSEMENTS;

	    private int AMORTISSEMENTS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;

	    private int AMORTISSEMENTS_TOTAL_DONT_AUTRES_IMMOBILISATIONS_INCORPORELLES;

	    private int AMORTISSEMENTS_TOTAL_IMMOBILISATIONS_CORPORELLES;

	    private int AMORTISSEMENTS_TOTAL_GENERAL;

	    private int MVT_SUR_CHARGES_REP_PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS;

	    private int PROVISIONS;

	    private int AMORTISSEMENTS_DEROGATOIRES;

	    private int TOTAL_PROVISIONS_REGLEMENTEES;

	    private int PROVISIONS_POUR_LITIGES;

	    private int PROVISIONS_POUR_GARANTIES_DONNEES_AUX_CLIENTS;

	    private int PROVISIONS_POUR_PERTE_SUR_MARCHES_A_TERME;

	    private int PROVISIONS_POUR_AMENDES_ET_PENALITES;

	    private int PROVISIONS_POUR_PERTE_DE_CHANGE;

	    private int PROVISIONS_POUR_PENSIONS_ET_OBLIGATIONS_SIMILAIRES;

	    private int PROVISIONS_POUR_IMPOTS;

	    private int PROVISIONS_POUR_RENOUVELLEMENT_DES_IMMOBILISATIONS;

	    private int PROVISIONS_POUR_GROS_ENTRETIEN_ET_GRANDES_REVISIONS_OU_GROSSES_REPARATIONS;

	    private int PROVISIONS_POUR_CHARGES_SOCIALES_ET_FISCALES_SUR_CONGES_A_PAYER;

	    private int AUTRES_PROVISIONS_POUR_RISQUES_ET_CHARGES;

	    private int TOTAL_PROVISIONS_POUR_RISQUES_ET_CHARGES;

	    private int SUR_IMMOBILISATIONS_INCORPORELLES;

	    private int SUR_IMMOBILISATIONS_CORPORELLES;

	    private int SUR_IMMOBILISATIONS_TITRES_MIS_EN_EQUIVALENCE;

	    private int SUR_IMMOBILISATIONS_TITRES_DE_PARTICIPATION;

	    private int SUR_IMMOBILISATIONS_AUTRES_IMMOBILISATIONS_FINANCIERES;

	    private int SUR_STOCKS_ET_EN_COURS;

	    private int SUR_COMPTES_CLIENTS;

	    private int AUTRES_PROVISIONS_POUR_DEPRECIATION;

	    private int TOTAL_PROVISIONS_POUR_DEPRECIATION;

	    private int TOTAL_GENERAL;

	    private int DONT_DOTATIONS_ET_REPRISES_D_EXPLOITATION;

	    private int DONT_DOTATIONS_ET_REPRISES_FINANCIERES;

	    private int DONT_DOTATIONS_ET_REPRISES_EXCEPTIONNELLES;

	    private int CREANCES_ET_DETTES;

	    private int CLIENTS_DOUTEUX_OU_LITIGIEUX;

	    private int AUTRES_CREANCES_CLIENTS;

	    private int PROVISION_POUR_DEPRECIATION_ANTERIEUREMENT_CONSTITUEE;

	    private int CREANCES_REPRESENTATIVES_DE_TITRES_PRETES;

	    private int PERSONNEL_ET_COMPTES_RATTACHES;

	    private int SECURITE_SOCIALE_AUTRES_ORGANISMES_SOCIAUX;

	    private int IMPOTS_SUR_LES_BENEFICES;

	    private int T_V_A;

	    private int AUTRES_IMPOTS_TAXES_VERSEMENTS_ASSIMILES;

	    private int DIVERS;

	    private int GROUPE_ET_ASSOCIES;

	    private int DEBITEURS_DIVERS_DONT_CREANCES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRES;

	    private int TOTAL_ETAT_DES_CREANCES;

	    private int EMPRUNTS_OBLIGATAIRES_CONVERTIBLES_BRUT_A_UN_AN_AU_PLUS;

	    private int AUTRES_EMPRUNTS_OBLIGATAIRES_BRUT_A_UN_AN_AU_PLUS;

	    private int EMPRUNTS_A_1_AN_MAXIMUM_A_L_ORIGINE;

	    private int EMPRUNTS_A_PLUS_D_1_AN_A_L_ORIGINE;

	    private int EMPRUNTS_ET_DETTES_FINANCIERES_DIVERS;

	    private int FOURNISSEURS_ET_COMPTES_RATTACHES;

	    private int SECURITE_SOCIALE_ET_AUTRES_ORGANISMES_SOCIAUX;

	    private int TVA;

	    private int OBLIGATIONS_CAUTIONNEES;

	    private int AUTRES_IMPOTS_TAXES_ET_ASSIMILES;

	    private int AUTRES_DETTES_DONT_DETTES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRE;

	    private int DETTE_REPRESENTATIVE_DE_TITRES_EMPRUNTES;

	    private int PRODUITS_CONSTATES_D_AVANCE;

	    private int TOTAL_ETAT_DES_DETTES;

	    private int EMPRUNTS_SOUSCRITS_EN_COURS_D_EXERCICE;

	    private int EMPRUNTS_REMBOURSES_EN_COURS_D_EXERCICE;

	    private int AFFECTATION_DU_RESULTAT_RENSEIGNEMENTS_DIVERS;

	    private int DIVIDENDES;

	    private int ENGAGEMENT_DE_CREDITBAIL_MOBILIER;

	    private int ENGAGEMENT_DE_CREDITBAIL_IMMOBILIER;

	    private int EFFETS_PORTES_A_L_ESCOMPTE_ET_NON_ECHUS;

	    private int SOUSTRAITANCE;

	    private int LOCATION_CHARGES_LOCATIVES_ET_DE_COPROPRIETE;

	    private int PERSONNEL_EXTERIEUR_A_L_ENTREPRISE;

	    private int REMUNERATION_D_INTERMEDIAIRES_ET_HONORAIRES_HORS_RETROCESSIONS;

	    private int RETROCESSIONS_D_HONORAIRES_COMMISSIONS_ET_COURTAGES;

	    private int AUTRES_COMPTES;

	    private int TOTAL_DU_POSTE_CORRESPONDANT_A_LA_LIGNE_FW_DU_TABLEAU_NUMERO_2052;

	    private int TAXE_PROFESSIONNELLE;

	    private int AUTRES_IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES;

	    private int TOTAL_DU_COMPTE_CORRESPONDANT_A_LA_LIGNE_FX_DU_TABLEAU_NUMERO_2052;

	    private int MONTANT_DE_LA_TVA_COLLECTEE;

	    private int TOTAL_TVA_DEDUCTIBLE_SUR_BIENS_ET_SERVICES;

	    private int EFFECTIF_MOYEN_DU_PERSONNEL;

	    private int FILIALES_ET_PARTICIPATIONS;
	

	public  List<String> getStringAttributsName() throws BeanException
	{
		List<String> stringAttributs = new ArrayList<String>();
		Field[] f = this.getClass().getDeclaredFields();
		//System.out.println("recherche des noms des attributs : "+f.length);
		for(int i = 0 ; i < 8 ; i++)
		{
			if(f[i].getType().getSimpleName().equals("String")) {
				stringAttributs.add(f[i].getName());
			}
			//System.out.println(" simple: "+f[i].getType().getSimpleName());
		}
		return stringAttributs;
	}
	
	public List<String> getAttributsName() throws BeanException
	{
		List<String> Attributs = new ArrayList<String>();
		Field[] f = this.getClass().getDeclaredFields();
		//System.out.println("recherche des noms des attributs : "+f.length);
		for(int i = 0 ; i < f.length ; i++)
		{
			//if(o.equals(f[i].get(this))) //Comparaison de deux variable 
			Attributs.add(f[i].getName());
			//System.out.println(" simple: "+f[i].getType().getSimpleName());
		}
		return Attributs;
	}

	public String getSIREN() {
		return SIREN;
	}

	public void setSIREN(String sIREN) {
		SIREN = sIREN;
	}

	public int getACTIF() {
		return ACTIF;
	}

	public void setACTIF(int aCTIF) {
		ACTIF = aCTIF;
	}

	public int getCAPITAL_SOUSCRIT_NON_APPELE() {
		return CAPITAL_SOUSCRIT_NON_APPELE;
	}

	public void setCAPITAL_SOUSCRIT_NON_APPELE(int cAPITAL_SOUSCRIT_NON_APPELE) {
		CAPITAL_SOUSCRIT_NON_APPELE = cAPITAL_SOUSCRIT_NON_APPELE;
	}

	public int getFRAIS_D_ETABLISSEMENT() {
		return FRAIS_D_ETABLISSEMENT;
	}

	public void setFRAIS_D_ETABLISSEMENT(int fRAIS_D_ETABLISSEMENT) {
		FRAIS_D_ETABLISSEMENT = fRAIS_D_ETABLISSEMENT;
	}

	public int getFRAIS_DE_DEVELOPPEMENT_OU_DE_RECHERCHE_ET_DEVELOPPEMENT() {
		return FRAIS_DE_DEVELOPPEMENT_OU_DE_RECHERCHE_ET_DEVELOPPEMENT;
	}

	public void setFRAIS_DE_DEVELOPPEMENT_OU_DE_RECHERCHE_ET_DEVELOPPEMENT(
			int fRAIS_DE_DEVELOPPEMENT_OU_DE_RECHERCHE_ET_DEVELOPPEMENT) {
		FRAIS_DE_DEVELOPPEMENT_OU_DE_RECHERCHE_ET_DEVELOPPEMENT = fRAIS_DE_DEVELOPPEMENT_OU_DE_RECHERCHE_ET_DEVELOPPEMENT;
	}

	public int getCONCESSIONS_BREVETS_ET_DROITS_SIMILAIRES() {
		return CONCESSIONS_BREVETS_ET_DROITS_SIMILAIRES;
	}

	public void setCONCESSIONS_BREVETS_ET_DROITS_SIMILAIRES(int cONCESSIONS_BREVETS_ET_DROITS_SIMILAIRES) {
		CONCESSIONS_BREVETS_ET_DROITS_SIMILAIRES = cONCESSIONS_BREVETS_ET_DROITS_SIMILAIRES;
	}

	public int getFONDS_COMMERCIAL() {
		return FONDS_COMMERCIAL;
	}

	public void setFONDS_COMMERCIAL(int fONDS_COMMERCIAL) {
		FONDS_COMMERCIAL = fONDS_COMMERCIAL;
	}

	public int getAUTRES_IMMOBILISATIONS_INCORPORELLES() {
		return AUTRES_IMMOBILISATIONS_INCORPORELLES;
	}

	public void setAUTRES_IMMOBILISATIONS_INCORPORELLES(int aUTRES_IMMOBILISATIONS_INCORPORELLES) {
		AUTRES_IMMOBILISATIONS_INCORPORELLES = aUTRES_IMMOBILISATIONS_INCORPORELLES;
	}

	public int getAVANCES_ET_ACOMPTES_SUR_IMMOBILISATIONS_INCORPORELLES() {
		return AVANCES_ET_ACOMPTES_SUR_IMMOBILISATIONS_INCORPORELLES;
	}

	public void setAVANCES_ET_ACOMPTES_SUR_IMMOBILISATIONS_INCORPORELLES(
			int aVANCES_ET_ACOMPTES_SUR_IMMOBILISATIONS_INCORPORELLES) {
		AVANCES_ET_ACOMPTES_SUR_IMMOBILISATIONS_INCORPORELLES = aVANCES_ET_ACOMPTES_SUR_IMMOBILISATIONS_INCORPORELLES;
	}

	public int getTERRAINS() {
		return TERRAINS;
	}

	public void setTERRAINS(int tERRAINS) {
		TERRAINS = tERRAINS;
	}

	public int getCONSTRUCTIONS() {
		return CONSTRUCTIONS;
	}

	public void setCONSTRUCTIONS(int cONSTRUCTIONS) {
		CONSTRUCTIONS = cONSTRUCTIONS;
	}

	public int getINSTALLATIONS_TECHNIQUES_MATERIEL_ET_OUTILLAGE_INDUSTRIELS() {
		return INSTALLATIONS_TECHNIQUES_MATERIEL_ET_OUTILLAGE_INDUSTRIELS;
	}

	public void setINSTALLATIONS_TECHNIQUES_MATERIEL_ET_OUTILLAGE_INDUSTRIELS(
			int iNSTALLATIONS_TECHNIQUES_MATERIEL_ET_OUTILLAGE_INDUSTRIELS) {
		INSTALLATIONS_TECHNIQUES_MATERIEL_ET_OUTILLAGE_INDUSTRIELS = iNSTALLATIONS_TECHNIQUES_MATERIEL_ET_OUTILLAGE_INDUSTRIELS;
	}

	public int getAUTRES_IMMOBILISATIONS_CORPORELLES() {
		return AUTRES_IMMOBILISATIONS_CORPORELLES;
	}

	public void setAUTRES_IMMOBILISATIONS_CORPORELLES(int aUTRES_IMMOBILISATIONS_CORPORELLES) {
		AUTRES_IMMOBILISATIONS_CORPORELLES = aUTRES_IMMOBILISATIONS_CORPORELLES;
	}

	public int getIMMOBILISATIONS_EN_COURS() {
		return IMMOBILISATIONS_EN_COURS;
	}

	public void setIMMOBILISATIONS_EN_COURS(int iMMOBILISATIONS_EN_COURS) {
		IMMOBILISATIONS_EN_COURS = iMMOBILISATIONS_EN_COURS;
	}

	public int getAVANCES_ET_ACOMPTES() {
		return AVANCES_ET_ACOMPTES;
	}

	public void setAVANCES_ET_ACOMPTES(int aVANCES_ET_ACOMPTES) {
		AVANCES_ET_ACOMPTES = aVANCES_ET_ACOMPTES;
	}

	public int getPARTICIPATIONS_EVALUEES_MISE_EN_EQUIVALENCE() {
		return PARTICIPATIONS_EVALUEES_MISE_EN_EQUIVALENCE;
	}

	public void setPARTICIPATIONS_EVALUEES_MISE_EN_EQUIVALENCE(int pARTICIPATIONS_EVALUEES_MISE_EN_EQUIVALENCE) {
		PARTICIPATIONS_EVALUEES_MISE_EN_EQUIVALENCE = pARTICIPATIONS_EVALUEES_MISE_EN_EQUIVALENCE;
	}

	public int getAUTRES_PARTICIPATIONS() {
		return AUTRES_PARTICIPATIONS;
	}

	public void setAUTRES_PARTICIPATIONS(int aUTRES_PARTICIPATIONS) {
		AUTRES_PARTICIPATIONS = aUTRES_PARTICIPATIONS;
	}

	public int getCREANCES_RATTACHEES_A_DES_PARTICIPATIONS() {
		return CREANCES_RATTACHEES_A_DES_PARTICIPATIONS;
	}

	public void setCREANCES_RATTACHEES_A_DES_PARTICIPATIONS(int cREANCES_RATTACHEES_A_DES_PARTICIPATIONS) {
		CREANCES_RATTACHEES_A_DES_PARTICIPATIONS = cREANCES_RATTACHEES_A_DES_PARTICIPATIONS;
	}

	public int getAUTRES_TITRES_IMMOBILISES() {
		return AUTRES_TITRES_IMMOBILISES;
	}

	public void setAUTRES_TITRES_IMMOBILISES(int aUTRES_TITRES_IMMOBILISES) {
		AUTRES_TITRES_IMMOBILISES = aUTRES_TITRES_IMMOBILISES;
	}

	public int getPRETS() {
		return PRETS;
	}

	public void setPRETS(int pRETS) {
		PRETS = pRETS;
	}

	public int getAUTRES_IMMOBILISATIONS_FINANCIERES() {
		return AUTRES_IMMOBILISATIONS_FINANCIERES;
	}

	public void setAUTRES_IMMOBILISATIONS_FINANCIERES(int aUTRES_IMMOBILISATIONS_FINANCIERES) {
		AUTRES_IMMOBILISATIONS_FINANCIERES = aUTRES_IMMOBILISATIONS_FINANCIERES;
	}

	public int getTOTAL_I() {
		return TOTAL_I;
	}

	public void setTOTAL_I(int tOTAL_I) {
		TOTAL_I = tOTAL_I;
	}

	public int getMATIERES_PREMIERES_APPROVISIONNEMENTS() {
		return MATIERES_PREMIERES_APPROVISIONNEMENTS;
	}

	public void setMATIERES_PREMIERES_APPROVISIONNEMENTS(int mATIERES_PREMIERES_APPROVISIONNEMENTS) {
		MATIERES_PREMIERES_APPROVISIONNEMENTS = mATIERES_PREMIERES_APPROVISIONNEMENTS;
	}

	public int getEN_COURS_DE_PRODUCTION_DE_BIENS() {
		return EN_COURS_DE_PRODUCTION_DE_BIENS;
	}

	public void setEN_COURS_DE_PRODUCTION_DE_BIENS(int eN_COURS_DE_PRODUCTION_DE_BIENS) {
		EN_COURS_DE_PRODUCTION_DE_BIENS = eN_COURS_DE_PRODUCTION_DE_BIENS;
	}

	public int getEN_COURS_DE_PRODUCTION_DE_SERVICES() {
		return EN_COURS_DE_PRODUCTION_DE_SERVICES;
	}

	public void setEN_COURS_DE_PRODUCTION_DE_SERVICES(int eN_COURS_DE_PRODUCTION_DE_SERVICES) {
		EN_COURS_DE_PRODUCTION_DE_SERVICES = eN_COURS_DE_PRODUCTION_DE_SERVICES;
	}

	public int getPRODUITS_INTERMEDIAIRES_ET_FINIS() {
		return PRODUITS_INTERMEDIAIRES_ET_FINIS;
	}

	public void setPRODUITS_INTERMEDIAIRES_ET_FINIS(int pRODUITS_INTERMEDIAIRES_ET_FINIS) {
		PRODUITS_INTERMEDIAIRES_ET_FINIS = pRODUITS_INTERMEDIAIRES_ET_FINIS;
	}

	public int getMARCHANDISES() {
		return MARCHANDISES;
	}

	public void setMARCHANDISES(int mARCHANDISES) {
		MARCHANDISES = mARCHANDISES;
	}

	public int getAVANCES_ET_ACOMPTES_VERSES_SUR_COMMANDES() {
		return AVANCES_ET_ACOMPTES_VERSES_SUR_COMMANDES;
	}

	public void setAVANCES_ET_ACOMPTES_VERSES_SUR_COMMANDES(int aVANCES_ET_ACOMPTES_VERSES_SUR_COMMANDES) {
		AVANCES_ET_ACOMPTES_VERSES_SUR_COMMANDES = aVANCES_ET_ACOMPTES_VERSES_SUR_COMMANDES;
	}

	public int getCLIENTS_ET_COMPTES_RATTACHES() {
		return CLIENTS_ET_COMPTES_RATTACHES;
	}

	public void setCLIENTS_ET_COMPTES_RATTACHES(int cLIENTS_ET_COMPTES_RATTACHES) {
		CLIENTS_ET_COMPTES_RATTACHES = cLIENTS_ET_COMPTES_RATTACHES;
	}

	public int getAUTRES_CREANCES() {
		return AUTRES_CREANCES;
	}

	public void setAUTRES_CREANCES(int aUTRES_CREANCES) {
		AUTRES_CREANCES = aUTRES_CREANCES;
	}

	public int getCAPITAL_SOUSCRIT_ET_APPELE_NON_VERSE() {
		return CAPITAL_SOUSCRIT_ET_APPELE_NON_VERSE;
	}

	public void setCAPITAL_SOUSCRIT_ET_APPELE_NON_VERSE(int cAPITAL_SOUSCRIT_ET_APPELE_NON_VERSE) {
		CAPITAL_SOUSCRIT_ET_APPELE_NON_VERSE = cAPITAL_SOUSCRIT_ET_APPELE_NON_VERSE;
	}

	public int getVALEURS_MOBILIERES_DE_PLACEMENT() {
		return VALEURS_MOBILIERES_DE_PLACEMENT;
	}

	public void setVALEURS_MOBILIERES_DE_PLACEMENT(int vALEURS_MOBILIERES_DE_PLACEMENT) {
		VALEURS_MOBILIERES_DE_PLACEMENT = vALEURS_MOBILIERES_DE_PLACEMENT;
	}

	public int getDISPONIBILITES() {
		return DISPONIBILITES;
	}

	public void setDISPONIBILITES(int dISPONIBILITES) {
		DISPONIBILITES = dISPONIBILITES;
	}

	public int getCHARGES_CONSTATEES_D_AVANCE() {
		return CHARGES_CONSTATEES_D_AVANCE;
	}

	public void setCHARGES_CONSTATEES_D_AVANCE(int cHARGES_CONSTATEES_D_AVANCE) {
		CHARGES_CONSTATEES_D_AVANCE = cHARGES_CONSTATEES_D_AVANCE;
	}

	public int getTOTAL_II() {
		return TOTAL_II;
	}

	public void setTOTAL_II(int tOTAL_II) {
		TOTAL_II = tOTAL_II;
	}

	public int getCHARGES_A_REPARTIR_OU_FRAIS_D_EMISSION_D_EMPRUNT() {
		return CHARGES_A_REPARTIR_OU_FRAIS_D_EMISSION_D_EMPRUNT;
	}

	public void setCHARGES_A_REPARTIR_OU_FRAIS_D_EMISSION_D_EMPRUNT(int cHARGES_A_REPARTIR_OU_FRAIS_D_EMISSION_D_EMPRUNT) {
		CHARGES_A_REPARTIR_OU_FRAIS_D_EMISSION_D_EMPRUNT = cHARGES_A_REPARTIR_OU_FRAIS_D_EMISSION_D_EMPRUNT;
	}

	public int getPRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS_IV() {
		return PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS_IV;
	}

	public void setPRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS_IV(int pRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS_IV) {
		PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS_IV = pRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS_IV;
	}

	public int getECARTS_DE_CONVERSION_ACTIF_V() {
		return ECARTS_DE_CONVERSION_ACTIF_V;
	}

	public void setECARTS_DE_CONVERSION_ACTIF_V(int eCARTS_DE_CONVERSION_ACTIF_V) {
		ECARTS_DE_CONVERSION_ACTIF_V = eCARTS_DE_CONVERSION_ACTIF_V;
	}

	public int getTOTAL_GENERAL_0_A_V() {
		return TOTAL_GENERAL_0_A_V;
	}

	public void setTOTAL_GENERAL_0_A_V(int tOTAL_GENERAL_0_A_V) {
		TOTAL_GENERAL_0_A_V = tOTAL_GENERAL_0_A_V;
	}

	public int getPARTS_A_MOINS_D_UN_AN() {
		return PARTS_A_MOINS_D_UN_AN;
	}

	public void setPARTS_A_MOINS_D_UN_AN(int pARTS_A_MOINS_D_UN_AN) {
		PARTS_A_MOINS_D_UN_AN = pARTS_A_MOINS_D_UN_AN;
	}

	public int getPARTS_A_PLUS_D_UN_AN() {
		return PARTS_A_PLUS_D_UN_AN;
	}

	public void setPARTS_A_PLUS_D_UN_AN(int pARTS_A_PLUS_D_UN_AN) {
		PARTS_A_PLUS_D_UN_AN = pARTS_A_PLUS_D_UN_AN;
	}

	public int getPASSIF() {
		return PASSIF;
	}

	public void setPASSIF(int pASSIF) {
		PASSIF = pASSIF;
	}

	public int getCAPITAL_SOCIAL_OU_INDIVIDUEL() {
		return CAPITAL_SOCIAL_OU_INDIVIDUEL;
	}

	public void setCAPITAL_SOCIAL_OU_INDIVIDUEL(int cAPITAL_SOCIAL_OU_INDIVIDUEL) {
		CAPITAL_SOCIAL_OU_INDIVIDUEL = cAPITAL_SOCIAL_OU_INDIVIDUEL;
	}

	public int getPRIMES_D_EMISSION_DE_FUSION_D_APPORT() {
		return PRIMES_D_EMISSION_DE_FUSION_D_APPORT;
	}

	public void setPRIMES_D_EMISSION_DE_FUSION_D_APPORT(int pRIMES_D_EMISSION_DE_FUSION_D_APPORT) {
		PRIMES_D_EMISSION_DE_FUSION_D_APPORT = pRIMES_D_EMISSION_DE_FUSION_D_APPORT;
	}

	public int getDONT_ECART_D_EQUIVALENCE() {
		return DONT_ECART_D_EQUIVALENCE;
	}

	public void setDONT_ECART_D_EQUIVALENCE(int dONT_ECART_D_EQUIVALENCE) {
		DONT_ECART_D_EQUIVALENCE = dONT_ECART_D_EQUIVALENCE;
	}

	public int getECARTS_DE_REEVALUATION() {
		return ECARTS_DE_REEVALUATION;
	}

	public void setECARTS_DE_REEVALUATION(int eCARTS_DE_REEVALUATION) {
		ECARTS_DE_REEVALUATION = eCARTS_DE_REEVALUATION;
	}

	public int getRESERVE_LEGALE_1() {
		return RESERVE_LEGALE_1;
	}

	public void setRESERVE_LEGALE_1(int rESERVE_LEGALE_1) {
		RESERVE_LEGALE_1 = rESERVE_LEGALE_1;
	}

	public int getRESERVES_STATUTAIRES_OU_CONTRACTUELLES() {
		return RESERVES_STATUTAIRES_OU_CONTRACTUELLES;
	}

	public void setRESERVES_STATUTAIRES_OU_CONTRACTUELLES(int rESERVES_STATUTAIRES_OU_CONTRACTUELLES) {
		RESERVES_STATUTAIRES_OU_CONTRACTUELLES = rESERVES_STATUTAIRES_OU_CONTRACTUELLES;
	}

	public int getDONT_RESERVE_SPECIALE_DES_PROVISIONS_POUR_FLUCTUATION_DES_COURS() {
		return DONT_RESERVE_SPECIALE_DES_PROVISIONS_POUR_FLUCTUATION_DES_COURS;
	}

	public void setDONT_RESERVE_SPECIALE_DES_PROVISIONS_POUR_FLUCTUATION_DES_COURS(
			int dONT_RESERVE_SPECIALE_DES_PROVISIONS_POUR_FLUCTUATION_DES_COURS) {
		DONT_RESERVE_SPECIALE_DES_PROVISIONS_POUR_FLUCTUATION_DES_COURS = dONT_RESERVE_SPECIALE_DES_PROVISIONS_POUR_FLUCTUATION_DES_COURS;
	}

	public int getRESERVES_REGLEMENTEES_1() {
		return RESERVES_REGLEMENTEES_1;
	}

	public void setRESERVES_REGLEMENTEES_1(int rESERVES_REGLEMENTEES_1) {
		RESERVES_REGLEMENTEES_1 = rESERVES_REGLEMENTEES_1;
	}

	public int getDONT_RESERVE_RELATIVE_A_L_ACHAT_D_OEUVRES_ORIGINALES_D_ARTISTES_VIVANTS() {
		return DONT_RESERVE_RELATIVE_A_L_ACHAT_D_OEUVRES_ORIGINALES_D_ARTISTES_VIVANTS;
	}

	public void setDONT_RESERVE_RELATIVE_A_L_ACHAT_D_OEUVRES_ORIGINALES_D_ARTISTES_VIVANTS(
			int dONT_RESERVE_RELATIVE_A_L_ACHAT_D_OEUVRES_ORIGINALES_D_ARTISTES_VIVANTS) {
		DONT_RESERVE_RELATIVE_A_L_ACHAT_D_OEUVRES_ORIGINALES_D_ARTISTES_VIVANTS = dONT_RESERVE_RELATIVE_A_L_ACHAT_D_OEUVRES_ORIGINALES_D_ARTISTES_VIVANTS;
	}

	public int getAUTRES_RESERVES() {
		return AUTRES_RESERVES;
	}

	public void setAUTRES_RESERVES(int aUTRES_RESERVES) {
		AUTRES_RESERVES = aUTRES_RESERVES;
	}

	public int getREPORT_A_NOUVEAU() {
		return REPORT_A_NOUVEAU;
	}

	public void setREPORT_A_NOUVEAU(int rEPORT_A_NOUVEAU) {
		REPORT_A_NOUVEAU = rEPORT_A_NOUVEAU;
	}

	public int getRESULTAT_DE_L_EXERCICE_BENEFICE_OU_PERTE() {
		return RESULTAT_DE_L_EXERCICE_BENEFICE_OU_PERTE;
	}

	public void setRESULTAT_DE_L_EXERCICE_BENEFICE_OU_PERTE(int rESULTAT_DE_L_EXERCICE_BENEFICE_OU_PERTE) {
		RESULTAT_DE_L_EXERCICE_BENEFICE_OU_PERTE = rESULTAT_DE_L_EXERCICE_BENEFICE_OU_PERTE;
	}

	public int getSUBVENTIONS_D_INVESTISSEMENT() {
		return SUBVENTIONS_D_INVESTISSEMENT;
	}

	public void setSUBVENTIONS_D_INVESTISSEMENT(int sUBVENTIONS_D_INVESTISSEMENT) {
		SUBVENTIONS_D_INVESTISSEMENT = sUBVENTIONS_D_INVESTISSEMENT;
	}

	public int getPROVISIONS_REGLEMENTEES() {
		return PROVISIONS_REGLEMENTEES;
	}

	public void setPROVISIONS_REGLEMENTEES(int pROVISIONS_REGLEMENTEES) {
		PROVISIONS_REGLEMENTEES = pROVISIONS_REGLEMENTEES;
	}

	public int getPRODUIT_DES_EMISSIONS_DE_TITRES_PARTICIPATIFS() {
		return PRODUIT_DES_EMISSIONS_DE_TITRES_PARTICIPATIFS;
	}

	public void setPRODUIT_DES_EMISSIONS_DE_TITRES_PARTICIPATIFS(int pRODUIT_DES_EMISSIONS_DE_TITRES_PARTICIPATIFS) {
		PRODUIT_DES_EMISSIONS_DE_TITRES_PARTICIPATIFS = pRODUIT_DES_EMISSIONS_DE_TITRES_PARTICIPATIFS;
	}

	public int getAVANCES_CONDITIONNEES() {
		return AVANCES_CONDITIONNEES;
	}

	public void setAVANCES_CONDITIONNEES(int aVANCES_CONDITIONNEES) {
		AVANCES_CONDITIONNEES = aVANCES_CONDITIONNEES;
	}

	public int getPROVISIONS_POUR_RISQUES() {
		return PROVISIONS_POUR_RISQUES;
	}

	public void setPROVISIONS_POUR_RISQUES(int pROVISIONS_POUR_RISQUES) {
		PROVISIONS_POUR_RISQUES = pROVISIONS_POUR_RISQUES;
	}

	public int getPROVISIONS_POUR_CHARGES() {
		return PROVISIONS_POUR_CHARGES;
	}

	public void setPROVISIONS_POUR_CHARGES(int pROVISIONS_POUR_CHARGES) {
		PROVISIONS_POUR_CHARGES = pROVISIONS_POUR_CHARGES;
	}

	public int getTOTAL_III() {
		return TOTAL_III;
	}

	public void setTOTAL_III(int tOTAL_III) {
		TOTAL_III = tOTAL_III;
	}

	public int getEMPRUNTS_OBLIGATAIRES_CONVERTIBLES() {
		return EMPRUNTS_OBLIGATAIRES_CONVERTIBLES;
	}

	public void setEMPRUNTS_OBLIGATAIRES_CONVERTIBLES(int eMPRUNTS_OBLIGATAIRES_CONVERTIBLES) {
		EMPRUNTS_OBLIGATAIRES_CONVERTIBLES = eMPRUNTS_OBLIGATAIRES_CONVERTIBLES;
	}

	public int getAUTRES_EMPRUNTS_OBLIGATAIRES() {
		return AUTRES_EMPRUNTS_OBLIGATAIRES;
	}

	public void setAUTRES_EMPRUNTS_OBLIGATAIRES(int aUTRES_EMPRUNTS_OBLIGATAIRES) {
		AUTRES_EMPRUNTS_OBLIGATAIRES = aUTRES_EMPRUNTS_OBLIGATAIRES;
	}

	public int getEMPRUNTS_ET_DETTES_AUPRES_DES_ETABLISSEMENTS_DE_CREDIT_3() {
		return EMPRUNTS_ET_DETTES_AUPRES_DES_ETABLISSEMENTS_DE_CREDIT_3;
	}

	public void setEMPRUNTS_ET_DETTES_AUPRES_DES_ETABLISSEMENTS_DE_CREDIT_3(
			int eMPRUNTS_ET_DETTES_AUPRES_DES_ETABLISSEMENTS_DE_CREDIT_3) {
		EMPRUNTS_ET_DETTES_AUPRES_DES_ETABLISSEMENTS_DE_CREDIT_3 = eMPRUNTS_ET_DETTES_AUPRES_DES_ETABLISSEMENTS_DE_CREDIT_3;
	}

	public int getEMPRUNTS_ET_DETTES_FINANCIERES_DIVERS_4() {
		return EMPRUNTS_ET_DETTES_FINANCIERES_DIVERS_4;
	}

	public void setEMPRUNTS_ET_DETTES_FINANCIERES_DIVERS_4(int eMPRUNTS_ET_DETTES_FINANCIERES_DIVERS_4) {
		EMPRUNTS_ET_DETTES_FINANCIERES_DIVERS_4 = eMPRUNTS_ET_DETTES_FINANCIERES_DIVERS_4;
	}

	public int getAVANCES_ET_ACOMPTES_RECUS_SUR_COMMANDES_EN_COURS() {
		return AVANCES_ET_ACOMPTES_RECUS_SUR_COMMANDES_EN_COURS;
	}

	public void setAVANCES_ET_ACOMPTES_RECUS_SUR_COMMANDES_EN_COURS(int aVANCES_ET_ACOMPTES_RECUS_SUR_COMMANDES_EN_COURS) {
		AVANCES_ET_ACOMPTES_RECUS_SUR_COMMANDES_EN_COURS = aVANCES_ET_ACOMPTES_RECUS_SUR_COMMANDES_EN_COURS;
	}

	public int getDETTES_FOURNISSEURS_ET_COMPTES_RATTACHES() {
		return DETTES_FOURNISSEURS_ET_COMPTES_RATTACHES;
	}

	public void setDETTES_FOURNISSEURS_ET_COMPTES_RATTACHES(int dETTES_FOURNISSEURS_ET_COMPTES_RATTACHES) {
		DETTES_FOURNISSEURS_ET_COMPTES_RATTACHES = dETTES_FOURNISSEURS_ET_COMPTES_RATTACHES;
	}

	public int getDETTES_FISCALES_ET_SOCIALES() {
		return DETTES_FISCALES_ET_SOCIALES;
	}

	public void setDETTES_FISCALES_ET_SOCIALES(int dETTES_FISCALES_ET_SOCIALES) {
		DETTES_FISCALES_ET_SOCIALES = dETTES_FISCALES_ET_SOCIALES;
	}

	public int getDETTES_SUR_IMMOBILISATIONS_ET_COMPTES_RATTACHES() {
		return DETTES_SUR_IMMOBILISATIONS_ET_COMPTES_RATTACHES;
	}

	public void setDETTES_SUR_IMMOBILISATIONS_ET_COMPTES_RATTACHES(int dETTES_SUR_IMMOBILISATIONS_ET_COMPTES_RATTACHES) {
		DETTES_SUR_IMMOBILISATIONS_ET_COMPTES_RATTACHES = dETTES_SUR_IMMOBILISATIONS_ET_COMPTES_RATTACHES;
	}

	public int getAUTRES_DETTES() {
		return AUTRES_DETTES;
	}

	public void setAUTRES_DETTES(int aUTRES_DETTES) {
		AUTRES_DETTES = aUTRES_DETTES;
	}

	public int getPRODUITS_CONSTATES_D_AVANCE_2() {
		return PRODUITS_CONSTATES_D_AVANCE_2;
	}

	public void setPRODUITS_CONSTATES_D_AVANCE_2(int pRODUITS_CONSTATES_D_AVANCE_2) {
		PRODUITS_CONSTATES_D_AVANCE_2 = pRODUITS_CONSTATES_D_AVANCE_2;
	}

	public int getTOTAL_IV() {
		return TOTAL_IV;
	}

	public void setTOTAL_IV(int tOTAL_IV) {
		TOTAL_IV = tOTAL_IV;
	}

	public int getV() {
		return V;
	}

	public void setV(int v) {
		V = v;
	}

	public int getTOTAL_GENERAL_I_A_V() {
		return TOTAL_GENERAL_I_A_V;
	}

	public void setTOTAL_GENERAL_I_A_V(int tOTAL_GENERAL_I_A_V) {
		TOTAL_GENERAL_I_A_V = tOTAL_GENERAL_I_A_V;
	}

	public int getDONT_RESERVE_REGLEMENTEE_DES_PLUSVALUES_A_LONG_TERME() {
		return DONT_RESERVE_REGLEMENTEE_DES_PLUSVALUES_A_LONG_TERME;
	}

	public void setDONT_RESERVE_REGLEMENTEE_DES_PLUSVALUES_A_LONG_TERME(
			int dONT_RESERVE_REGLEMENTEE_DES_PLUSVALUES_A_LONG_TERME) {
		DONT_RESERVE_REGLEMENTEE_DES_PLUSVALUES_A_LONG_TERME = dONT_RESERVE_REGLEMENTEE_DES_PLUSVALUES_A_LONG_TERME;
	}

	public int getDETTES_ET_PRODUITS_CONSTATES_D_AVANCE_A_MOINS_D_UN_AN() {
		return DETTES_ET_PRODUITS_CONSTATES_D_AVANCE_A_MOINS_D_UN_AN;
	}

	public void setDETTES_ET_PRODUITS_CONSTATES_D_AVANCE_A_MOINS_D_UN_AN(
			int dETTES_ET_PRODUITS_CONSTATES_D_AVANCE_A_MOINS_D_UN_AN) {
		DETTES_ET_PRODUITS_CONSTATES_D_AVANCE_A_MOINS_D_UN_AN = dETTES_ET_PRODUITS_CONSTATES_D_AVANCE_A_MOINS_D_UN_AN;
	}

	public int getDONT_CONCOURS_BANCAIRES_COURANTS_ET_SOLDES_CREDITEURS_DE_BANQUES_ET_CCP() {
		return DONT_CONCOURS_BANCAIRES_COURANTS_ET_SOLDES_CREDITEURS_DE_BANQUES_ET_CCP;
	}

	public void setDONT_CONCOURS_BANCAIRES_COURANTS_ET_SOLDES_CREDITEURS_DE_BANQUES_ET_CCP(
			int dONT_CONCOURS_BANCAIRES_COURANTS_ET_SOLDES_CREDITEURS_DE_BANQUES_ET_CCP) {
		DONT_CONCOURS_BANCAIRES_COURANTS_ET_SOLDES_CREDITEURS_DE_BANQUES_ET_CCP = dONT_CONCOURS_BANCAIRES_COURANTS_ET_SOLDES_CREDITEURS_DE_BANQUES_ET_CCP;
	}

	public int getDONT_EMPRUNTS_PARTICIPATIFS() {
		return DONT_EMPRUNTS_PARTICIPATIFS;
	}

	public void setDONT_EMPRUNTS_PARTICIPATIFS(int dONT_EMPRUNTS_PARTICIPATIFS) {
		DONT_EMPRUNTS_PARTICIPATIFS = dONT_EMPRUNTS_PARTICIPATIFS;
	}

	public int getCOMPTE_DE_RESULTAT_A() {
		return COMPTE_DE_RESULTAT_A;
	}

	public void setCOMPTE_DE_RESULTAT_A(int cOMPTE_DE_RESULTAT_A) {
		COMPTE_DE_RESULTAT_A = cOMPTE_DE_RESULTAT_A;
	}

	public int getVENTES_DE_MARCHANDISES() {
		return VENTES_DE_MARCHANDISES;
	}

	public void setVENTES_DE_MARCHANDISES(int vENTES_DE_MARCHANDISES) {
		VENTES_DE_MARCHANDISES = vENTES_DE_MARCHANDISES;
	}

	public int getPRODUCTION_VENDUE_BIENS() {
		return PRODUCTION_VENDUE_BIENS;
	}

	public void setPRODUCTION_VENDUE_BIENS(int pRODUCTION_VENDUE_BIENS) {
		PRODUCTION_VENDUE_BIENS = pRODUCTION_VENDUE_BIENS;
	}

	public int getPRODUCTION_VENDUE_SERVICES() {
		return PRODUCTION_VENDUE_SERVICES;
	}

	public void setPRODUCTION_VENDUE_SERVICES(int pRODUCTION_VENDUE_SERVICES) {
		PRODUCTION_VENDUE_SERVICES = pRODUCTION_VENDUE_SERVICES;
	}

	public int getCHIFFRES_D_AFFAIRES_NETS() {
		return CHIFFRES_D_AFFAIRES_NETS;
	}

	public void setCHIFFRES_D_AFFAIRES_NETS(int cHIFFRES_D_AFFAIRES_NETS) {
		CHIFFRES_D_AFFAIRES_NETS = cHIFFRES_D_AFFAIRES_NETS;
	}

	public int getPRODUCTION_STOCKEE() {
		return PRODUCTION_STOCKEE;
	}

	public void setPRODUCTION_STOCKEE(int pRODUCTION_STOCKEE) {
		PRODUCTION_STOCKEE = pRODUCTION_STOCKEE;
	}

	public int getPRODUCTION_IMMOBILISEE() {
		return PRODUCTION_IMMOBILISEE;
	}

	public void setPRODUCTION_IMMOBILISEE(int pRODUCTION_IMMOBILISEE) {
		PRODUCTION_IMMOBILISEE = pRODUCTION_IMMOBILISEE;
	}

	public int getSUBVENTIONS_D_EXPLOITATION() {
		return SUBVENTIONS_D_EXPLOITATION;
	}

	public void setSUBVENTIONS_D_EXPLOITATION(int sUBVENTIONS_D_EXPLOITATION) {
		SUBVENTIONS_D_EXPLOITATION = sUBVENTIONS_D_EXPLOITATION;
	}

	public int getREPRISES_SUR_AMORTISSEMENTS_ET_PROVISIONS_TRANSFERT_DE_CHARGES() {
		return REPRISES_SUR_AMORTISSEMENTS_ET_PROVISIONS_TRANSFERT_DE_CHARGES;
	}

	public void setREPRISES_SUR_AMORTISSEMENTS_ET_PROVISIONS_TRANSFERT_DE_CHARGES(
			int rEPRISES_SUR_AMORTISSEMENTS_ET_PROVISIONS_TRANSFERT_DE_CHARGES) {
		REPRISES_SUR_AMORTISSEMENTS_ET_PROVISIONS_TRANSFERT_DE_CHARGES = rEPRISES_SUR_AMORTISSEMENTS_ET_PROVISIONS_TRANSFERT_DE_CHARGES;
	}

	public int getAUTRES_PRODUITS() {
		return AUTRES_PRODUITS;
	}

	public void setAUTRES_PRODUITS(int aUTRES_PRODUITS) {
		AUTRES_PRODUITS = aUTRES_PRODUITS;
	}

	public int getTOTAL_DES_PRODUITS_D_EXPLOITATION_I() {
		return TOTAL_DES_PRODUITS_D_EXPLOITATION_I;
	}

	public void setTOTAL_DES_PRODUITS_D_EXPLOITATION_I(int tOTAL_DES_PRODUITS_D_EXPLOITATION_I) {
		TOTAL_DES_PRODUITS_D_EXPLOITATION_I = tOTAL_DES_PRODUITS_D_EXPLOITATION_I;
	}

	public int getACHATS_DE_MARCHANDISES_Y_COMPRIS_DROITS_DE_DOUANE() {
		return ACHATS_DE_MARCHANDISES_Y_COMPRIS_DROITS_DE_DOUANE;
	}

	public void setACHATS_DE_MARCHANDISES_Y_COMPRIS_DROITS_DE_DOUANE(
			int aCHATS_DE_MARCHANDISES_Y_COMPRIS_DROITS_DE_DOUANE) {
		ACHATS_DE_MARCHANDISES_Y_COMPRIS_DROITS_DE_DOUANE = aCHATS_DE_MARCHANDISES_Y_COMPRIS_DROITS_DE_DOUANE;
	}

	public int getVARIATION_DE_STOCK_MARCHANDISES() {
		return VARIATION_DE_STOCK_MARCHANDISES;
	}

	public void setVARIATION_DE_STOCK_MARCHANDISES(int vARIATION_DE_STOCK_MARCHANDISES) {
		VARIATION_DE_STOCK_MARCHANDISES = vARIATION_DE_STOCK_MARCHANDISES;
	}

	public int getACHATS_DE_MATIERES_PREMIERES_ET_AUTRES_APPROVISIONNEMENTS() {
		return ACHATS_DE_MATIERES_PREMIERES_ET_AUTRES_APPROVISIONNEMENTS;
	}

	public void setACHATS_DE_MATIERES_PREMIERES_ET_AUTRES_APPROVISIONNEMENTS(
			int aCHATS_DE_MATIERES_PREMIERES_ET_AUTRES_APPROVISIONNEMENTS) {
		ACHATS_DE_MATIERES_PREMIERES_ET_AUTRES_APPROVISIONNEMENTS = aCHATS_DE_MATIERES_PREMIERES_ET_AUTRES_APPROVISIONNEMENTS;
	}

	public int getVARIATION_DE_STOCK_MATIERES_PREMIERES_ET_APPROVISIONNEMENTS() {
		return VARIATION_DE_STOCK_MATIERES_PREMIERES_ET_APPROVISIONNEMENTS;
	}

	public void setVARIATION_DE_STOCK_MATIERES_PREMIERES_ET_APPROVISIONNEMENTS(
			int vARIATION_DE_STOCK_MATIERES_PREMIERES_ET_APPROVISIONNEMENTS) {
		VARIATION_DE_STOCK_MATIERES_PREMIERES_ET_APPROVISIONNEMENTS = vARIATION_DE_STOCK_MATIERES_PREMIERES_ET_APPROVISIONNEMENTS;
	}

	public int getAUTRES_ACHATS_ET_CHARGES_EXTERNES() {
		return AUTRES_ACHATS_ET_CHARGES_EXTERNES;
	}

	public void setAUTRES_ACHATS_ET_CHARGES_EXTERNES(int aUTRES_ACHATS_ET_CHARGES_EXTERNES) {
		AUTRES_ACHATS_ET_CHARGES_EXTERNES = aUTRES_ACHATS_ET_CHARGES_EXTERNES;
	}

	public int getIMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES() {
		return IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES;
	}

	public void setIMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES(int iMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES) {
		IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES = iMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES;
	}

	public int getSALAIRES_ET_TRAITEMENTS() {
		return SALAIRES_ET_TRAITEMENTS;
	}

	public void setSALAIRES_ET_TRAITEMENTS(int sALAIRES_ET_TRAITEMENTS) {
		SALAIRES_ET_TRAITEMENTS = sALAIRES_ET_TRAITEMENTS;
	}

	public int getCHARGES_SOCIALES() {
		return CHARGES_SOCIALES;
	}

	public void setCHARGES_SOCIALES(int cHARGES_SOCIALES) {
		CHARGES_SOCIALES = cHARGES_SOCIALES;
	}

	public int getDOT_D_EXPLOIT_DOTATIONS_AUX_AMORTISSEMENTS() {
		return DOT_D_EXPLOIT_DOTATIONS_AUX_AMORTISSEMENTS;
	}

	public void setDOT_D_EXPLOIT_DOTATIONS_AUX_AMORTISSEMENTS(int dOT_D_EXPLOIT_DOTATIONS_AUX_AMORTISSEMENTS) {
		DOT_D_EXPLOIT_DOTATIONS_AUX_AMORTISSEMENTS = dOT_D_EXPLOIT_DOTATIONS_AUX_AMORTISSEMENTS;
	}

	public int getDOT_D_EXPLOIT_DOTATIONS_AUX_PROVISIONS() {
		return DOT_D_EXPLOIT_DOTATIONS_AUX_PROVISIONS;
	}

	public void setDOT_D_EXPLOIT_DOTATIONS_AUX_PROVISIONS(int dOT_D_EXPLOIT_DOTATIONS_AUX_PROVISIONS) {
		DOT_D_EXPLOIT_DOTATIONS_AUX_PROVISIONS = dOT_D_EXPLOIT_DOTATIONS_AUX_PROVISIONS;
	}

	public int getDOT_D_EXPLOIT_SUR_ACTIF_CIRCULANT_DOTATIONS_AUX_PROVISIONS() {
		return DOT_D_EXPLOIT_SUR_ACTIF_CIRCULANT_DOTATIONS_AUX_PROVISIONS;
	}

	public void setDOT_D_EXPLOIT_SUR_ACTIF_CIRCULANT_DOTATIONS_AUX_PROVISIONS(
			int dOT_D_EXPLOIT_SUR_ACTIF_CIRCULANT_DOTATIONS_AUX_PROVISIONS) {
		DOT_D_EXPLOIT_SUR_ACTIF_CIRCULANT_DOTATIONS_AUX_PROVISIONS = dOT_D_EXPLOIT_SUR_ACTIF_CIRCULANT_DOTATIONS_AUX_PROVISIONS;
	}

	public int getDOT_D_EXPLOIT_POUR_RISQUES_ET_CHARGES_DOTATIONS_AUX_PROVISIONS() {
		return DOT_D_EXPLOIT_POUR_RISQUES_ET_CHARGES_DOTATIONS_AUX_PROVISIONS;
	}

	public void setDOT_D_EXPLOIT_POUR_RISQUES_ET_CHARGES_DOTATIONS_AUX_PROVISIONS(
			int dOT_D_EXPLOIT_POUR_RISQUES_ET_CHARGES_DOTATIONS_AUX_PROVISIONS) {
		DOT_D_EXPLOIT_POUR_RISQUES_ET_CHARGES_DOTATIONS_AUX_PROVISIONS = dOT_D_EXPLOIT_POUR_RISQUES_ET_CHARGES_DOTATIONS_AUX_PROVISIONS;
	}

	public int getAUTRES_CHARGES() {
		return AUTRES_CHARGES;
	}

	public void setAUTRES_CHARGES(int aUTRES_CHARGES) {
		AUTRES_CHARGES = aUTRES_CHARGES;
	}

	public int getTOTAL_DES_CHARGES_D_EXPLOITATION_II() {
		return TOTAL_DES_CHARGES_D_EXPLOITATION_II;
	}

	public void setTOTAL_DES_CHARGES_D_EXPLOITATION_II(int tOTAL_DES_CHARGES_D_EXPLOITATION_II) {
		TOTAL_DES_CHARGES_D_EXPLOITATION_II = tOTAL_DES_CHARGES_D_EXPLOITATION_II;
	}

	public int getRESULTAT_D_EXPLOITATION_I_II() {
		return RESULTAT_D_EXPLOITATION_I_II;
	}

	public void setRESULTAT_D_EXPLOITATION_I_II(int rESULTAT_D_EXPLOITATION_I_II) {
		RESULTAT_D_EXPLOITATION_I_II = rESULTAT_D_EXPLOITATION_I_II;
	}

	public int getBENEFICE_ATTRIBUE_OU_PERTE_TRANSFEREE_III() {
		return BENEFICE_ATTRIBUE_OU_PERTE_TRANSFEREE_III;
	}

	public void setBENEFICE_ATTRIBUE_OU_PERTE_TRANSFEREE_III(int bENEFICE_ATTRIBUE_OU_PERTE_TRANSFEREE_III) {
		BENEFICE_ATTRIBUE_OU_PERTE_TRANSFEREE_III = bENEFICE_ATTRIBUE_OU_PERTE_TRANSFEREE_III;
	}

	public int getPERTE_SUPPORTEE_OU_BENEFICE_TRANSFERE_IV() {
		return PERTE_SUPPORTEE_OU_BENEFICE_TRANSFERE_IV;
	}

	public void setPERTE_SUPPORTEE_OU_BENEFICE_TRANSFERE_IV(int pERTE_SUPPORTEE_OU_BENEFICE_TRANSFERE_IV) {
		PERTE_SUPPORTEE_OU_BENEFICE_TRANSFERE_IV = pERTE_SUPPORTEE_OU_BENEFICE_TRANSFERE_IV;
	}

	public int getPRODUITS_FINANCIERS_DE_PARTICIPATIONS() {
		return PRODUITS_FINANCIERS_DE_PARTICIPATIONS;
	}

	public void setPRODUITS_FINANCIERS_DE_PARTICIPATIONS(int pRODUITS_FINANCIERS_DE_PARTICIPATIONS) {
		PRODUITS_FINANCIERS_DE_PARTICIPATIONS = pRODUITS_FINANCIERS_DE_PARTICIPATIONS;
	}

	public int getPRODUITS_DES_AUTRES_VALEURS_MOBILIERES_ET_CREANCES_DE_L_ACTIF_IMMOBILISE() {
		return PRODUITS_DES_AUTRES_VALEURS_MOBILIERES_ET_CREANCES_DE_L_ACTIF_IMMOBILISE;
	}

	public void setPRODUITS_DES_AUTRES_VALEURS_MOBILIERES_ET_CREANCES_DE_L_ACTIF_IMMOBILISE(
			int pRODUITS_DES_AUTRES_VALEURS_MOBILIERES_ET_CREANCES_DE_L_ACTIF_IMMOBILISE) {
		PRODUITS_DES_AUTRES_VALEURS_MOBILIERES_ET_CREANCES_DE_L_ACTIF_IMMOBILISE = pRODUITS_DES_AUTRES_VALEURS_MOBILIERES_ET_CREANCES_DE_L_ACTIF_IMMOBILISE;
	}

	public int getAUTRES_INTERETS_ET_PRODUITS_ASSIMILES() {
		return AUTRES_INTERETS_ET_PRODUITS_ASSIMILES;
	}

	public void setAUTRES_INTERETS_ET_PRODUITS_ASSIMILES(int aUTRES_INTERETS_ET_PRODUITS_ASSIMILES) {
		AUTRES_INTERETS_ET_PRODUITS_ASSIMILES = aUTRES_INTERETS_ET_PRODUITS_ASSIMILES;
	}

	public int getREPRISES_SUR_PROVISIONS_ET_TRANSFERTS_DE_CHARGES() {
		return REPRISES_SUR_PROVISIONS_ET_TRANSFERTS_DE_CHARGES;
	}

	public void setREPRISES_SUR_PROVISIONS_ET_TRANSFERTS_DE_CHARGES(int rEPRISES_SUR_PROVISIONS_ET_TRANSFERTS_DE_CHARGES) {
		REPRISES_SUR_PROVISIONS_ET_TRANSFERTS_DE_CHARGES = rEPRISES_SUR_PROVISIONS_ET_TRANSFERTS_DE_CHARGES;
	}

	public int getDIFFERENCES_POSITIVES_DE_CHANGE() {
		return DIFFERENCES_POSITIVES_DE_CHANGE;
	}

	public void setDIFFERENCES_POSITIVES_DE_CHANGE(int dIFFERENCES_POSITIVES_DE_CHANGE) {
		DIFFERENCES_POSITIVES_DE_CHANGE = dIFFERENCES_POSITIVES_DE_CHANGE;
	}

	public int getPRODUITS_NETS_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT() {
		return PRODUITS_NETS_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT;
	}

	public void setPRODUITS_NETS_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT(
			int pRODUITS_NETS_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT) {
		PRODUITS_NETS_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT = pRODUITS_NETS_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT;
	}

	public int getTOTAL_DES_PRODUITS_FINANCIERS_V() {
		return TOTAL_DES_PRODUITS_FINANCIERS_V;
	}

	public void setTOTAL_DES_PRODUITS_FINANCIERS_V(int tOTAL_DES_PRODUITS_FINANCIERS_V) {
		TOTAL_DES_PRODUITS_FINANCIERS_V = tOTAL_DES_PRODUITS_FINANCIERS_V;
	}

	public int getDOTATIONS_FINANCIERES_SUR_AMORTISSEMENTS_ET_PROVISIONS() {
		return DOTATIONS_FINANCIERES_SUR_AMORTISSEMENTS_ET_PROVISIONS;
	}

	public void setDOTATIONS_FINANCIERES_SUR_AMORTISSEMENTS_ET_PROVISIONS(
			int dOTATIONS_FINANCIERES_SUR_AMORTISSEMENTS_ET_PROVISIONS) {
		DOTATIONS_FINANCIERES_SUR_AMORTISSEMENTS_ET_PROVISIONS = dOTATIONS_FINANCIERES_SUR_AMORTISSEMENTS_ET_PROVISIONS;
	}

	public int getINTERETS_ET_CHARGES_ASSIMILEES() {
		return INTERETS_ET_CHARGES_ASSIMILEES;
	}

	public void setINTERETS_ET_CHARGES_ASSIMILEES(int iNTERETS_ET_CHARGES_ASSIMILEES) {
		INTERETS_ET_CHARGES_ASSIMILEES = iNTERETS_ET_CHARGES_ASSIMILEES;
	}

	public int getDIFFERENCES_NEGATIVES_DE_CHANGE() {
		return DIFFERENCES_NEGATIVES_DE_CHANGE;
	}

	public void setDIFFERENCES_NEGATIVES_DE_CHANGE(int dIFFERENCES_NEGATIVES_DE_CHANGE) {
		DIFFERENCES_NEGATIVES_DE_CHANGE = dIFFERENCES_NEGATIVES_DE_CHANGE;
	}

	public int getCHARGES_NETTES_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT() {
		return CHARGES_NETTES_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT;
	}

	public void setCHARGES_NETTES_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT(
			int cHARGES_NETTES_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT) {
		CHARGES_NETTES_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT = cHARGES_NETTES_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT;
	}

	public int getTOTAL_DES_CHARGES_FINANCIERES_VI() {
		return TOTAL_DES_CHARGES_FINANCIERES_VI;
	}

	public void setTOTAL_DES_CHARGES_FINANCIERES_VI(int tOTAL_DES_CHARGES_FINANCIERES_VI) {
		TOTAL_DES_CHARGES_FINANCIERES_VI = tOTAL_DES_CHARGES_FINANCIERES_VI;
	}

	public int getRESULTAT_FINANCIER_V_VI() {
		return RESULTAT_FINANCIER_V_VI;
	}

	public void setRESULTAT_FINANCIER_V_VI(int rESULTAT_FINANCIER_V_VI) {
		RESULTAT_FINANCIER_V_VI = rESULTAT_FINANCIER_V_VI;
	}

	public int getRESULTAT_COURANT_AVANT_IMPOTS_I_II_III_IV_V_VI() {
		return RESULTAT_COURANT_AVANT_IMPOTS_I_II_III_IV_V_VI;
	}

	public void setRESULTAT_COURANT_AVANT_IMPOTS_I_II_III_IV_V_VI(int rESULTAT_COURANT_AVANT_IMPOTS_I_II_III_IV_V_VI) {
		RESULTAT_COURANT_AVANT_IMPOTS_I_II_III_IV_V_VI = rESULTAT_COURANT_AVANT_IMPOTS_I_II_III_IV_V_VI;
	}

	public int getCOMPTE_DE_RESULTAT_B() {
		return COMPTE_DE_RESULTAT_B;
	}

	public void setCOMPTE_DE_RESULTAT_B(int cOMPTE_DE_RESULTAT_B) {
		COMPTE_DE_RESULTAT_B = cOMPTE_DE_RESULTAT_B;
	}

	public int getPRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_DE_GESTION() {
		return PRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_DE_GESTION;
	}

	public void setPRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_DE_GESTION(int pRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_DE_GESTION) {
		PRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_DE_GESTION = pRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_DE_GESTION;
	}

	public int getPRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_EN_CAPITAL() {
		return PRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_EN_CAPITAL;
	}

	public void setPRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_EN_CAPITAL(int pRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_EN_CAPITAL) {
		PRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_EN_CAPITAL = pRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_EN_CAPITAL;
	}

	public int getTOTAL_DES_PRODUITS_EXCEPTIONNELS_VII() {
		return TOTAL_DES_PRODUITS_EXCEPTIONNELS_VII;
	}

	public void setTOTAL_DES_PRODUITS_EXCEPTIONNELS_VII(int tOTAL_DES_PRODUITS_EXCEPTIONNELS_VII) {
		TOTAL_DES_PRODUITS_EXCEPTIONNELS_VII = tOTAL_DES_PRODUITS_EXCEPTIONNELS_VII;
	}

	public int getCHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_DE_GESTION() {
		return CHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_DE_GESTION;
	}

	public void setCHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_DE_GESTION(
			int cHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_DE_GESTION) {
		CHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_DE_GESTION = cHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_DE_GESTION;
	}

	public int getCHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_EN_CAPITAL() {
		return CHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_EN_CAPITAL;
	}

	public void setCHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_EN_CAPITAL(
			int cHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_EN_CAPITAL) {
		CHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_EN_CAPITAL = cHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_EN_CAPITAL;
	}

	public int getDOTATIONS_EXCEPTIONNELLES_AUX_AMORTISSEMENTS_ET_PROVISIONS() {
		return DOTATIONS_EXCEPTIONNELLES_AUX_AMORTISSEMENTS_ET_PROVISIONS;
	}

	public void setDOTATIONS_EXCEPTIONNELLES_AUX_AMORTISSEMENTS_ET_PROVISIONS(
			int dOTATIONS_EXCEPTIONNELLES_AUX_AMORTISSEMENTS_ET_PROVISIONS) {
		DOTATIONS_EXCEPTIONNELLES_AUX_AMORTISSEMENTS_ET_PROVISIONS = dOTATIONS_EXCEPTIONNELLES_AUX_AMORTISSEMENTS_ET_PROVISIONS;
	}

	public int getTOTAL_DES_CHARGES_EXCEPTIONNELLES_VIII() {
		return TOTAL_DES_CHARGES_EXCEPTIONNELLES_VIII;
	}

	public void setTOTAL_DES_CHARGES_EXCEPTIONNELLES_VIII(int tOTAL_DES_CHARGES_EXCEPTIONNELLES_VIII) {
		TOTAL_DES_CHARGES_EXCEPTIONNELLES_VIII = tOTAL_DES_CHARGES_EXCEPTIONNELLES_VIII;
	}

	public int getRESULTAT_EXCEPTIONNEL_VII_VIII() {
		return RESULTAT_EXCEPTIONNEL_VII_VIII;
	}

	public void setRESULTAT_EXCEPTIONNEL_VII_VIII(int rESULTAT_EXCEPTIONNEL_VII_VIII) {
		RESULTAT_EXCEPTIONNEL_VII_VIII = rESULTAT_EXCEPTIONNEL_VII_VIII;
	}

	public int getPARTICIPATION_DES_SALARIES_AUX_RESULTATS_DE_L_ENTREPRISE() {
		return PARTICIPATION_DES_SALARIES_AUX_RESULTATS_DE_L_ENTREPRISE;
	}

	public void setPARTICIPATION_DES_SALARIES_AUX_RESULTATS_DE_L_ENTREPRISE(
			int pARTICIPATION_DES_SALARIES_AUX_RESULTATS_DE_L_ENTREPRISE) {
		PARTICIPATION_DES_SALARIES_AUX_RESULTATS_DE_L_ENTREPRISE = pARTICIPATION_DES_SALARIES_AUX_RESULTATS_DE_L_ENTREPRISE;
	}

	public int getIMPOTS_SUR_LES_BENEFICES_X() {
		return IMPOTS_SUR_LES_BENEFICES_X;
	}

	public void setIMPOTS_SUR_LES_BENEFICES_X(int iMPOTS_SUR_LES_BENEFICES_X) {
		IMPOTS_SUR_LES_BENEFICES_X = iMPOTS_SUR_LES_BENEFICES_X;
	}

	public int getTOTAL_DES_PRODUITS_I_III_V_VII() {
		return TOTAL_DES_PRODUITS_I_III_V_VII;
	}

	public void setTOTAL_DES_PRODUITS_I_III_V_VII(int tOTAL_DES_PRODUITS_I_III_V_VII) {
		TOTAL_DES_PRODUITS_I_III_V_VII = tOTAL_DES_PRODUITS_I_III_V_VII;
	}

	public int getTOTAL_DES_CHARGES_II_IV_VI_VIII_IX_X() {
		return TOTAL_DES_CHARGES_II_IV_VI_VIII_IX_X;
	}

	public void setTOTAL_DES_CHARGES_II_IV_VI_VIII_IX_X(int tOTAL_DES_CHARGES_II_IV_VI_VIII_IX_X) {
		TOTAL_DES_CHARGES_II_IV_VI_VIII_IX_X = tOTAL_DES_CHARGES_II_IV_VI_VIII_IX_X;
	}

	public int getBENEFICE_OU_PERTE_TOTAL_DES_PRODUITS_TOTAL_DES_CHARGES() {
		return BENEFICE_OU_PERTE_TOTAL_DES_PRODUITS_TOTAL_DES_CHARGES;
	}

	public void setBENEFICE_OU_PERTE_TOTAL_DES_PRODUITS_TOTAL_DES_CHARGES(
			int bENEFICE_OU_PERTE_TOTAL_DES_PRODUITS_TOTAL_DES_CHARGES) {
		BENEFICE_OU_PERTE_TOTAL_DES_PRODUITS_TOTAL_DES_CHARGES = bENEFICE_OU_PERTE_TOTAL_DES_PRODUITS_TOTAL_DES_CHARGES;
	}

	public int getRENVOIS_CREDITBAIL_MOBILIER() {
		return RENVOIS_CREDITBAIL_MOBILIER;
	}

	public void setRENVOIS_CREDITBAIL_MOBILIER(int rENVOIS_CREDITBAIL_MOBILIER) {
		RENVOIS_CREDITBAIL_MOBILIER = rENVOIS_CREDITBAIL_MOBILIER;
	}

	public int getRENVOIS_CREDITBAIL_IMMOBILIER() {
		return RENVOIS_CREDITBAIL_IMMOBILIER;
	}

	public void setRENVOIS_CREDITBAIL_IMMOBILIER(int rENVOIS_CREDITBAIL_IMMOBILIER) {
		RENVOIS_CREDITBAIL_IMMOBILIER = rENVOIS_CREDITBAIL_IMMOBILIER;
	}

	public int getRENVOIS_TRANSFERT_DE_CHARGES() {
		return RENVOIS_TRANSFERT_DE_CHARGES;
	}

	public void setRENVOIS_TRANSFERT_DE_CHARGES(int rENVOIS_TRANSFERT_DE_CHARGES) {
		RENVOIS_TRANSFERT_DE_CHARGES = rENVOIS_TRANSFERT_DE_CHARGES;
	}

	public int getRENVOIS_COTISATIONS_PERSONNELLES_DE_L_EXPLOITANT() {
		return RENVOIS_COTISATIONS_PERSONNELLES_DE_L_EXPLOITANT;
	}

	public void setRENVOIS_COTISATIONS_PERSONNELLES_DE_L_EXPLOITANT(int rENVOIS_COTISATIONS_PERSONNELLES_DE_L_EXPLOITANT) {
		RENVOIS_COTISATIONS_PERSONNELLES_DE_L_EXPLOITANT = rENVOIS_COTISATIONS_PERSONNELLES_DE_L_EXPLOITANT;
	}

	public int getRENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_PRODUITS() {
		return RENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_PRODUITS;
	}

	public void setRENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_PRODUITS(
			int rENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_PRODUITS) {
		RENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_PRODUITS = rENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_PRODUITS;
	}

	public int getRENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_CHARGES() {
		return RENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_CHARGES;
	}

	public void setRENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_CHARGES(
			int rENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_CHARGES) {
		RENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_CHARGES = rENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_CHARGES;
	}

	public int getIMMOBILISATIONS() {
		return IMMOBILISATIONS;
	}

	public void setIMMOBILISATIONS(int iMMOBILISATIONS) {
		IMMOBILISATIONS = iMMOBILISATIONS;
	}

	public int getACQUISITIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE() {
		return ACQUISITIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;
	}

	public void setACQUISITIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE(
			int aCQUISITIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE) {
		ACQUISITIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE = aCQUISITIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;
	}

	public int getACQUISITIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES() {
		return ACQUISITIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES;
	}

	public void setACQUISITIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES(
			int aCQUISITIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES) {
		ACQUISITIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES = aCQUISITIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES;
	}

	public int getACQUISITIONS_TOTAL_IMMOBILISATIONS_CORPORELLES() {
		return ACQUISITIONS_TOTAL_IMMOBILISATIONS_CORPORELLES;
	}

	public void setACQUISITIONS_TOTAL_IMMOBILISATIONS_CORPORELLES(int aCQUISITIONS_TOTAL_IMMOBILISATIONS_CORPORELLES) {
		ACQUISITIONS_TOTAL_IMMOBILISATIONS_CORPORELLES = aCQUISITIONS_TOTAL_IMMOBILISATIONS_CORPORELLES;
	}

	public int getACQUISITIONS_TOTAL_IMMOBILISATIONS_FINANCIERES() {
		return ACQUISITIONS_TOTAL_IMMOBILISATIONS_FINANCIERES;
	}

	public void setACQUISITIONS_TOTAL_IMMOBILISATIONS_FINANCIERES(int aCQUISITIONS_TOTAL_IMMOBILISATIONS_FINANCIERES) {
		ACQUISITIONS_TOTAL_IMMOBILISATIONS_FINANCIERES = aCQUISITIONS_TOTAL_IMMOBILISATIONS_FINANCIERES;
	}

	public int getACQUISITIONS_TOTAL_GENERAL() {
		return ACQUISITIONS_TOTAL_GENERAL;
	}

	public void setACQUISITIONS_TOTAL_GENERAL(int aCQUISITIONS_TOTAL_GENERAL) {
		ACQUISITIONS_TOTAL_GENERAL = aCQUISITIONS_TOTAL_GENERAL;
	}

	public int getDIMINUTIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE() {
		return DIMINUTIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;
	}

	public void setDIMINUTIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE(
			int dIMINUTIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE) {
		DIMINUTIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE = dIMINUTIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;
	}

	public int getDIMINUTIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES() {
		return DIMINUTIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES;
	}

	public void setDIMINUTIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES(
			int dIMINUTIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES) {
		DIMINUTIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES = dIMINUTIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES;
	}

	public int getDIMINUTIONS_VIREMENT_POSTES_IMMOBILISATIONS_CORPORELLES_EN_COURS() {
		return DIMINUTIONS_VIREMENT_POSTES_IMMOBILISATIONS_CORPORELLES_EN_COURS;
	}

	public void setDIMINUTIONS_VIREMENT_POSTES_IMMOBILISATIONS_CORPORELLES_EN_COURS(
			int dIMINUTIONS_VIREMENT_POSTES_IMMOBILISATIONS_CORPORELLES_EN_COURS) {
		DIMINUTIONS_VIREMENT_POSTES_IMMOBILISATIONS_CORPORELLES_EN_COURS = dIMINUTIONS_VIREMENT_POSTES_IMMOBILISATIONS_CORPORELLES_EN_COURS;
	}

	public int getDIMINUTIONS_VIREMENT_POSTES_AVANCES_ET_ACOMPTES() {
		return DIMINUTIONS_VIREMENT_POSTES_AVANCES_ET_ACOMPTES;
	}

	public void setDIMINUTIONS_VIREMENT_POSTES_AVANCES_ET_ACOMPTES(int dIMINUTIONS_VIREMENT_POSTES_AVANCES_ET_ACOMPTES) {
		DIMINUTIONS_VIREMENT_POSTES_AVANCES_ET_ACOMPTES = dIMINUTIONS_VIREMENT_POSTES_AVANCES_ET_ACOMPTES;
	}

	public int getDIMINUTIONS_TOTAL_IMMOBILISATIONS_CORPORELLES() {
		return DIMINUTIONS_TOTAL_IMMOBILISATIONS_CORPORELLES;
	}

	public void setDIMINUTIONS_TOTAL_IMMOBILISATIONS_CORPORELLES(int dIMINUTIONS_TOTAL_IMMOBILISATIONS_CORPORELLES) {
		DIMINUTIONS_TOTAL_IMMOBILISATIONS_CORPORELLES = dIMINUTIONS_TOTAL_IMMOBILISATIONS_CORPORELLES;
	}

	public int getDIMINUTIONS_PRETS_ET_IMMOBILISATIONS_FINANCIERES() {
		return DIMINUTIONS_PRETS_ET_IMMOBILISATIONS_FINANCIERES;
	}

	public void setDIMINUTIONS_PRETS_ET_IMMOBILISATIONS_FINANCIERES(int dIMINUTIONS_PRETS_ET_IMMOBILISATIONS_FINANCIERES) {
		DIMINUTIONS_PRETS_ET_IMMOBILISATIONS_FINANCIERES = dIMINUTIONS_PRETS_ET_IMMOBILISATIONS_FINANCIERES;
	}

	public int getDIMINUTIONS_TOTAL_IMMOBILISATIONS_FINANCIERES() {
		return DIMINUTIONS_TOTAL_IMMOBILISATIONS_FINANCIERES;
	}

	public void setDIMINUTIONS_TOTAL_IMMOBILISATIONS_FINANCIERES(int dIMINUTIONS_TOTAL_IMMOBILISATIONS_FINANCIERES) {
		DIMINUTIONS_TOTAL_IMMOBILISATIONS_FINANCIERES = dIMINUTIONS_TOTAL_IMMOBILISATIONS_FINANCIERES;
	}

	public int getDIMINUTIONS_TOTAL_GENERAL() {
		return DIMINUTIONS_TOTAL_GENERAL;
	}

	public void setDIMINUTIONS_TOTAL_GENERAL(int dIMINUTIONS_TOTAL_GENERAL) {
		DIMINUTIONS_TOTAL_GENERAL = dIMINUTIONS_TOTAL_GENERAL;
	}

	public int getAMORTISSEMENTS() {
		return AMORTISSEMENTS;
	}

	public void setAMORTISSEMENTS(int aMORTISSEMENTS) {
		AMORTISSEMENTS = aMORTISSEMENTS;
	}

	public int getAMORTISSEMENTS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE() {
		return AMORTISSEMENTS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;
	}

	public void setAMORTISSEMENTS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE(
			int aMORTISSEMENTS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE) {
		AMORTISSEMENTS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE = aMORTISSEMENTS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;
	}

	public int getAMORTISSEMENTS_TOTAL_DONT_AUTRES_IMMOBILISATIONS_INCORPORELLES() {
		return AMORTISSEMENTS_TOTAL_DONT_AUTRES_IMMOBILISATIONS_INCORPORELLES;
	}

	public void setAMORTISSEMENTS_TOTAL_DONT_AUTRES_IMMOBILISATIONS_INCORPORELLES(
			int aMORTISSEMENTS_TOTAL_DONT_AUTRES_IMMOBILISATIONS_INCORPORELLES) {
		AMORTISSEMENTS_TOTAL_DONT_AUTRES_IMMOBILISATIONS_INCORPORELLES = aMORTISSEMENTS_TOTAL_DONT_AUTRES_IMMOBILISATIONS_INCORPORELLES;
	}

	public int getAMORTISSEMENTS_TOTAL_IMMOBILISATIONS_CORPORELLES() {
		return AMORTISSEMENTS_TOTAL_IMMOBILISATIONS_CORPORELLES;
	}

	public void setAMORTISSEMENTS_TOTAL_IMMOBILISATIONS_CORPORELLES(int aMORTISSEMENTS_TOTAL_IMMOBILISATIONS_CORPORELLES) {
		AMORTISSEMENTS_TOTAL_IMMOBILISATIONS_CORPORELLES = aMORTISSEMENTS_TOTAL_IMMOBILISATIONS_CORPORELLES;
	}

	public int getAMORTISSEMENTS_TOTAL_GENERAL() {
		return AMORTISSEMENTS_TOTAL_GENERAL;
	}

	public void setAMORTISSEMENTS_TOTAL_GENERAL(int aMORTISSEMENTS_TOTAL_GENERAL) {
		AMORTISSEMENTS_TOTAL_GENERAL = aMORTISSEMENTS_TOTAL_GENERAL;
	}

	public int getMVT_SUR_CHARGES_REP_PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS() {
		return MVT_SUR_CHARGES_REP_PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS;
	}

	public void setMVT_SUR_CHARGES_REP_PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS(
			int mVT_SUR_CHARGES_REP_PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS) {
		MVT_SUR_CHARGES_REP_PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS = mVT_SUR_CHARGES_REP_PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS;
	}

	public int getPROVISIONS() {
		return PROVISIONS;
	}

	public void setPROVISIONS(int pROVISIONS) {
		PROVISIONS = pROVISIONS;
	}

	public int getAMORTISSEMENTS_DEROGATOIRES() {
		return AMORTISSEMENTS_DEROGATOIRES;
	}

	public void setAMORTISSEMENTS_DEROGATOIRES(int aMORTISSEMENTS_DEROGATOIRES) {
		AMORTISSEMENTS_DEROGATOIRES = aMORTISSEMENTS_DEROGATOIRES;
	}

	public int getTOTAL_PROVISIONS_REGLEMENTEES() {
		return TOTAL_PROVISIONS_REGLEMENTEES;
	}

	public void setTOTAL_PROVISIONS_REGLEMENTEES(int tOTAL_PROVISIONS_REGLEMENTEES) {
		TOTAL_PROVISIONS_REGLEMENTEES = tOTAL_PROVISIONS_REGLEMENTEES;
	}

	public int getPROVISIONS_POUR_LITIGES() {
		return PROVISIONS_POUR_LITIGES;
	}

	public void setPROVISIONS_POUR_LITIGES(int pROVISIONS_POUR_LITIGES) {
		PROVISIONS_POUR_LITIGES = pROVISIONS_POUR_LITIGES;
	}

	public int getPROVISIONS_POUR_GARANTIES_DONNEES_AUX_CLIENTS() {
		return PROVISIONS_POUR_GARANTIES_DONNEES_AUX_CLIENTS;
	}

	public void setPROVISIONS_POUR_GARANTIES_DONNEES_AUX_CLIENTS(int pROVISIONS_POUR_GARANTIES_DONNEES_AUX_CLIENTS) {
		PROVISIONS_POUR_GARANTIES_DONNEES_AUX_CLIENTS = pROVISIONS_POUR_GARANTIES_DONNEES_AUX_CLIENTS;
	}

	public int getPROVISIONS_POUR_PERTE_SUR_MARCHES_A_TERME() {
		return PROVISIONS_POUR_PERTE_SUR_MARCHES_A_TERME;
	}

	public void setPROVISIONS_POUR_PERTE_SUR_MARCHES_A_TERME(int pROVISIONS_POUR_PERTE_SUR_MARCHES_A_TERME) {
		PROVISIONS_POUR_PERTE_SUR_MARCHES_A_TERME = pROVISIONS_POUR_PERTE_SUR_MARCHES_A_TERME;
	}

	public int getPROVISIONS_POUR_AMENDES_ET_PENALITES() {
		return PROVISIONS_POUR_AMENDES_ET_PENALITES;
	}

	public void setPROVISIONS_POUR_AMENDES_ET_PENALITES(int pROVISIONS_POUR_AMENDES_ET_PENALITES) {
		PROVISIONS_POUR_AMENDES_ET_PENALITES = pROVISIONS_POUR_AMENDES_ET_PENALITES;
	}

	public int getPROVISIONS_POUR_PERTE_DE_CHANGE() {
		return PROVISIONS_POUR_PERTE_DE_CHANGE;
	}

	public void setPROVISIONS_POUR_PERTE_DE_CHANGE(int pROVISIONS_POUR_PERTE_DE_CHANGE) {
		PROVISIONS_POUR_PERTE_DE_CHANGE = pROVISIONS_POUR_PERTE_DE_CHANGE;
	}

	public int getPROVISIONS_POUR_PENSIONS_ET_OBLIGATIONS_SIMILAIRES() {
		return PROVISIONS_POUR_PENSIONS_ET_OBLIGATIONS_SIMILAIRES;
	}

	public void setPROVISIONS_POUR_PENSIONS_ET_OBLIGATIONS_SIMILAIRES(
			int pROVISIONS_POUR_PENSIONS_ET_OBLIGATIONS_SIMILAIRES) {
		PROVISIONS_POUR_PENSIONS_ET_OBLIGATIONS_SIMILAIRES = pROVISIONS_POUR_PENSIONS_ET_OBLIGATIONS_SIMILAIRES;
	}

	public int getPROVISIONS_POUR_IMPOTS() {
		return PROVISIONS_POUR_IMPOTS;
	}

	public void setPROVISIONS_POUR_IMPOTS(int pROVISIONS_POUR_IMPOTS) {
		PROVISIONS_POUR_IMPOTS = pROVISIONS_POUR_IMPOTS;
	}

	public int getPROVISIONS_POUR_RENOUVELLEMENT_DES_IMMOBILISATIONS() {
		return PROVISIONS_POUR_RENOUVELLEMENT_DES_IMMOBILISATIONS;
	}

	public void setPROVISIONS_POUR_RENOUVELLEMENT_DES_IMMOBILISATIONS(
			int pROVISIONS_POUR_RENOUVELLEMENT_DES_IMMOBILISATIONS) {
		PROVISIONS_POUR_RENOUVELLEMENT_DES_IMMOBILISATIONS = pROVISIONS_POUR_RENOUVELLEMENT_DES_IMMOBILISATIONS;
	}

	public int getPROVISIONS_POUR_GROS_ENTRETIEN_ET_GRANDES_REVISIONS_OU_GROSSES_REPARATIONS() {
		return PROVISIONS_POUR_GROS_ENTRETIEN_ET_GRANDES_REVISIONS_OU_GROSSES_REPARATIONS;
	}

	public void setPROVISIONS_POUR_GROS_ENTRETIEN_ET_GRANDES_REVISIONS_OU_GROSSES_REPARATIONS(
			int pROVISIONS_POUR_GROS_ENTRETIEN_ET_GRANDES_REVISIONS_OU_GROSSES_REPARATIONS) {
		PROVISIONS_POUR_GROS_ENTRETIEN_ET_GRANDES_REVISIONS_OU_GROSSES_REPARATIONS = pROVISIONS_POUR_GROS_ENTRETIEN_ET_GRANDES_REVISIONS_OU_GROSSES_REPARATIONS;
	}

	public int getPROVISIONS_POUR_CHARGES_SOCIALES_ET_FISCALES_SUR_CONGES_A_PAYER() {
		return PROVISIONS_POUR_CHARGES_SOCIALES_ET_FISCALES_SUR_CONGES_A_PAYER;
	}

	public void setPROVISIONS_POUR_CHARGES_SOCIALES_ET_FISCALES_SUR_CONGES_A_PAYER(
			int pROVISIONS_POUR_CHARGES_SOCIALES_ET_FISCALES_SUR_CONGES_A_PAYER) {
		PROVISIONS_POUR_CHARGES_SOCIALES_ET_FISCALES_SUR_CONGES_A_PAYER = pROVISIONS_POUR_CHARGES_SOCIALES_ET_FISCALES_SUR_CONGES_A_PAYER;
	}

	public int getAUTRES_PROVISIONS_POUR_RISQUES_ET_CHARGES() {
		return AUTRES_PROVISIONS_POUR_RISQUES_ET_CHARGES;
	}

	public void setAUTRES_PROVISIONS_POUR_RISQUES_ET_CHARGES(int aUTRES_PROVISIONS_POUR_RISQUES_ET_CHARGES) {
		AUTRES_PROVISIONS_POUR_RISQUES_ET_CHARGES = aUTRES_PROVISIONS_POUR_RISQUES_ET_CHARGES;
	}

	public int getTOTAL_PROVISIONS_POUR_RISQUES_ET_CHARGES() {
		return TOTAL_PROVISIONS_POUR_RISQUES_ET_CHARGES;
	}

	public void setTOTAL_PROVISIONS_POUR_RISQUES_ET_CHARGES(int tOTAL_PROVISIONS_POUR_RISQUES_ET_CHARGES) {
		TOTAL_PROVISIONS_POUR_RISQUES_ET_CHARGES = tOTAL_PROVISIONS_POUR_RISQUES_ET_CHARGES;
	}

	public int getSUR_IMMOBILISATIONS_INCORPORELLES() {
		return SUR_IMMOBILISATIONS_INCORPORELLES;
	}

	public void setSUR_IMMOBILISATIONS_INCORPORELLES(int sUR_IMMOBILISATIONS_INCORPORELLES) {
		SUR_IMMOBILISATIONS_INCORPORELLES = sUR_IMMOBILISATIONS_INCORPORELLES;
	}

	public int getSUR_IMMOBILISATIONS_CORPORELLES() {
		return SUR_IMMOBILISATIONS_CORPORELLES;
	}

	public void setSUR_IMMOBILISATIONS_CORPORELLES(int sUR_IMMOBILISATIONS_CORPORELLES) {
		SUR_IMMOBILISATIONS_CORPORELLES = sUR_IMMOBILISATIONS_CORPORELLES;
	}

	public int getSUR_IMMOBILISATIONS_TITRES_MIS_EN_EQUIVALENCE() {
		return SUR_IMMOBILISATIONS_TITRES_MIS_EN_EQUIVALENCE;
	}

	public void setSUR_IMMOBILISATIONS_TITRES_MIS_EN_EQUIVALENCE(int sUR_IMMOBILISATIONS_TITRES_MIS_EN_EQUIVALENCE) {
		SUR_IMMOBILISATIONS_TITRES_MIS_EN_EQUIVALENCE = sUR_IMMOBILISATIONS_TITRES_MIS_EN_EQUIVALENCE;
	}

	public int getSUR_IMMOBILISATIONS_TITRES_DE_PARTICIPATION() {
		return SUR_IMMOBILISATIONS_TITRES_DE_PARTICIPATION;
	}

	public void setSUR_IMMOBILISATIONS_TITRES_DE_PARTICIPATION(int sUR_IMMOBILISATIONS_TITRES_DE_PARTICIPATION) {
		SUR_IMMOBILISATIONS_TITRES_DE_PARTICIPATION = sUR_IMMOBILISATIONS_TITRES_DE_PARTICIPATION;
	}

	public int getSUR_IMMOBILISATIONS_AUTRES_IMMOBILISATIONS_FINANCIERES() {
		return SUR_IMMOBILISATIONS_AUTRES_IMMOBILISATIONS_FINANCIERES;
	}

	public void setSUR_IMMOBILISATIONS_AUTRES_IMMOBILISATIONS_FINANCIERES(
			int sUR_IMMOBILISATIONS_AUTRES_IMMOBILISATIONS_FINANCIERES) {
		SUR_IMMOBILISATIONS_AUTRES_IMMOBILISATIONS_FINANCIERES = sUR_IMMOBILISATIONS_AUTRES_IMMOBILISATIONS_FINANCIERES;
	}

	public int getSUR_STOCKS_ET_EN_COURS() {
		return SUR_STOCKS_ET_EN_COURS;
	}

	public void setSUR_STOCKS_ET_EN_COURS(int sUR_STOCKS_ET_EN_COURS) {
		SUR_STOCKS_ET_EN_COURS = sUR_STOCKS_ET_EN_COURS;
	}

	public int getSUR_COMPTES_CLIENTS() {
		return SUR_COMPTES_CLIENTS;
	}

	public void setSUR_COMPTES_CLIENTS(int sUR_COMPTES_CLIENTS) {
		SUR_COMPTES_CLIENTS = sUR_COMPTES_CLIENTS;
	}

	public int getAUTRES_PROVISIONS_POUR_DEPRECIATION() {
		return AUTRES_PROVISIONS_POUR_DEPRECIATION;
	}

	public void setAUTRES_PROVISIONS_POUR_DEPRECIATION(int aUTRES_PROVISIONS_POUR_DEPRECIATION) {
		AUTRES_PROVISIONS_POUR_DEPRECIATION = aUTRES_PROVISIONS_POUR_DEPRECIATION;
	}

	public int getTOTAL_PROVISIONS_POUR_DEPRECIATION() {
		return TOTAL_PROVISIONS_POUR_DEPRECIATION;
	}

	public void setTOTAL_PROVISIONS_POUR_DEPRECIATION(int tOTAL_PROVISIONS_POUR_DEPRECIATION) {
		TOTAL_PROVISIONS_POUR_DEPRECIATION = tOTAL_PROVISIONS_POUR_DEPRECIATION;
	}

	public int getTOTAL_GENERAL() {
		return TOTAL_GENERAL;
	}

	public void setTOTAL_GENERAL(int tOTAL_GENERAL) {
		TOTAL_GENERAL = tOTAL_GENERAL;
	}

	public int getDONT_DOTATIONS_ET_REPRISES_D_EXPLOITATION() {
		return DONT_DOTATIONS_ET_REPRISES_D_EXPLOITATION;
	}

	public void setDONT_DOTATIONS_ET_REPRISES_D_EXPLOITATION(int dONT_DOTATIONS_ET_REPRISES_D_EXPLOITATION) {
		DONT_DOTATIONS_ET_REPRISES_D_EXPLOITATION = dONT_DOTATIONS_ET_REPRISES_D_EXPLOITATION;
	}

	public int getDONT_DOTATIONS_ET_REPRISES_FINANCIERES() {
		return DONT_DOTATIONS_ET_REPRISES_FINANCIERES;
	}

	public void setDONT_DOTATIONS_ET_REPRISES_FINANCIERES(int dONT_DOTATIONS_ET_REPRISES_FINANCIERES) {
		DONT_DOTATIONS_ET_REPRISES_FINANCIERES = dONT_DOTATIONS_ET_REPRISES_FINANCIERES;
	}

	public int getDONT_DOTATIONS_ET_REPRISES_EXCEPTIONNELLES() {
		return DONT_DOTATIONS_ET_REPRISES_EXCEPTIONNELLES;
	}

	public void setDONT_DOTATIONS_ET_REPRISES_EXCEPTIONNELLES(int dONT_DOTATIONS_ET_REPRISES_EXCEPTIONNELLES) {
		DONT_DOTATIONS_ET_REPRISES_EXCEPTIONNELLES = dONT_DOTATIONS_ET_REPRISES_EXCEPTIONNELLES;
	}

	public int getCREANCES_ET_DETTES() {
		return CREANCES_ET_DETTES;
	}

	public void setCREANCES_ET_DETTES(int cREANCES_ET_DETTES) {
		CREANCES_ET_DETTES = cREANCES_ET_DETTES;
	}

	public int getCLIENTS_DOUTEUX_OU_LITIGIEUX() {
		return CLIENTS_DOUTEUX_OU_LITIGIEUX;
	}

	public void setCLIENTS_DOUTEUX_OU_LITIGIEUX(int cLIENTS_DOUTEUX_OU_LITIGIEUX) {
		CLIENTS_DOUTEUX_OU_LITIGIEUX = cLIENTS_DOUTEUX_OU_LITIGIEUX;
	}

	public int getAUTRES_CREANCES_CLIENTS() {
		return AUTRES_CREANCES_CLIENTS;
	}

	public void setAUTRES_CREANCES_CLIENTS(int aUTRES_CREANCES_CLIENTS) {
		AUTRES_CREANCES_CLIENTS = aUTRES_CREANCES_CLIENTS;
	}

	public int getPROVISION_POUR_DEPRECIATION_ANTERIEUREMENT_CONSTITUEE() {
		return PROVISION_POUR_DEPRECIATION_ANTERIEUREMENT_CONSTITUEE;
	}

	public void setPROVISION_POUR_DEPRECIATION_ANTERIEUREMENT_CONSTITUEE(
			int pROVISION_POUR_DEPRECIATION_ANTERIEUREMENT_CONSTITUEE) {
		PROVISION_POUR_DEPRECIATION_ANTERIEUREMENT_CONSTITUEE = pROVISION_POUR_DEPRECIATION_ANTERIEUREMENT_CONSTITUEE;
	}

	public int getCREANCES_REPRESENTATIVES_DE_TITRES_PRETES() {
		return CREANCES_REPRESENTATIVES_DE_TITRES_PRETES;
	}

	public void setCREANCES_REPRESENTATIVES_DE_TITRES_PRETES(int cREANCES_REPRESENTATIVES_DE_TITRES_PRETES) {
		CREANCES_REPRESENTATIVES_DE_TITRES_PRETES = cREANCES_REPRESENTATIVES_DE_TITRES_PRETES;
	}

	public int getPERSONNEL_ET_COMPTES_RATTACHES() {
		return PERSONNEL_ET_COMPTES_RATTACHES;
	}

	public void setPERSONNEL_ET_COMPTES_RATTACHES(int pERSONNEL_ET_COMPTES_RATTACHES) {
		PERSONNEL_ET_COMPTES_RATTACHES = pERSONNEL_ET_COMPTES_RATTACHES;
	}

	public int getSECURITE_SOCIALE_AUTRES_ORGANISMES_SOCIAUX() {
		return SECURITE_SOCIALE_AUTRES_ORGANISMES_SOCIAUX;
	}

	public void setSECURITE_SOCIALE_AUTRES_ORGANISMES_SOCIAUX(int sECURITE_SOCIALE_AUTRES_ORGANISMES_SOCIAUX) {
		SECURITE_SOCIALE_AUTRES_ORGANISMES_SOCIAUX = sECURITE_SOCIALE_AUTRES_ORGANISMES_SOCIAUX;
	}

	public int getIMPOTS_SUR_LES_BENEFICES() {
		return IMPOTS_SUR_LES_BENEFICES;
	}

	public void setIMPOTS_SUR_LES_BENEFICES(int iMPOTS_SUR_LES_BENEFICES) {
		IMPOTS_SUR_LES_BENEFICES = iMPOTS_SUR_LES_BENEFICES;
	}

	public int getT_V_A() {
		return T_V_A;
	}

	public void setT_V_A(int t_V_A) {
		T_V_A = t_V_A;
	}

	public int getAUTRES_IMPOTS_TAXES_VERSEMENTS_ASSIMILES() {
		return AUTRES_IMPOTS_TAXES_VERSEMENTS_ASSIMILES;
	}

	public void setAUTRES_IMPOTS_TAXES_VERSEMENTS_ASSIMILES(int aUTRES_IMPOTS_TAXES_VERSEMENTS_ASSIMILES) {
		AUTRES_IMPOTS_TAXES_VERSEMENTS_ASSIMILES = aUTRES_IMPOTS_TAXES_VERSEMENTS_ASSIMILES;
	}

	public int getDIVERS() {
		return DIVERS;
	}

	public void setDIVERS(int dIVERS) {
		DIVERS = dIVERS;
	}

	public int getGROUPE_ET_ASSOCIES() {
		return GROUPE_ET_ASSOCIES;
	}

	public void setGROUPE_ET_ASSOCIES(int gROUPE_ET_ASSOCIES) {
		GROUPE_ET_ASSOCIES = gROUPE_ET_ASSOCIES;
	}

	public int getDEBITEURS_DIVERS_DONT_CREANCES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRES() {
		return DEBITEURS_DIVERS_DONT_CREANCES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRES;
	}

	public void setDEBITEURS_DIVERS_DONT_CREANCES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRES(
			int dEBITEURS_DIVERS_DONT_CREANCES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRES) {
		DEBITEURS_DIVERS_DONT_CREANCES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRES = dEBITEURS_DIVERS_DONT_CREANCES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRES;
	}

	public int getTOTAL_ETAT_DES_CREANCES() {
		return TOTAL_ETAT_DES_CREANCES;
	}

	public void setTOTAL_ETAT_DES_CREANCES(int tOTAL_ETAT_DES_CREANCES) {
		TOTAL_ETAT_DES_CREANCES = tOTAL_ETAT_DES_CREANCES;
	}

	public int getEMPRUNTS_OBLIGATAIRES_CONVERTIBLES_BRUT_A_UN_AN_AU_PLUS() {
		return EMPRUNTS_OBLIGATAIRES_CONVERTIBLES_BRUT_A_UN_AN_AU_PLUS;
	}

	public void setEMPRUNTS_OBLIGATAIRES_CONVERTIBLES_BRUT_A_UN_AN_AU_PLUS(
			int eMPRUNTS_OBLIGATAIRES_CONVERTIBLES_BRUT_A_UN_AN_AU_PLUS) {
		EMPRUNTS_OBLIGATAIRES_CONVERTIBLES_BRUT_A_UN_AN_AU_PLUS = eMPRUNTS_OBLIGATAIRES_CONVERTIBLES_BRUT_A_UN_AN_AU_PLUS;
	}

	public int getAUTRES_EMPRUNTS_OBLIGATAIRES_BRUT_A_UN_AN_AU_PLUS() {
		return AUTRES_EMPRUNTS_OBLIGATAIRES_BRUT_A_UN_AN_AU_PLUS;
	}

	public void setAUTRES_EMPRUNTS_OBLIGATAIRES_BRUT_A_UN_AN_AU_PLUS(
			int aUTRES_EMPRUNTS_OBLIGATAIRES_BRUT_A_UN_AN_AU_PLUS) {
		AUTRES_EMPRUNTS_OBLIGATAIRES_BRUT_A_UN_AN_AU_PLUS = aUTRES_EMPRUNTS_OBLIGATAIRES_BRUT_A_UN_AN_AU_PLUS;
	}

	public int getEMPRUNTS_A_1_AN_MAXIMUM_A_L_ORIGINE() {
		return EMPRUNTS_A_1_AN_MAXIMUM_A_L_ORIGINE;
	}

	public void setEMPRUNTS_A_1_AN_MAXIMUM_A_L_ORIGINE(int eMPRUNTS_A_1_AN_MAXIMUM_A_L_ORIGINE) {
		EMPRUNTS_A_1_AN_MAXIMUM_A_L_ORIGINE = eMPRUNTS_A_1_AN_MAXIMUM_A_L_ORIGINE;
	}

	public int getEMPRUNTS_A_PLUS_D_1_AN_A_L_ORIGINE() {
		return EMPRUNTS_A_PLUS_D_1_AN_A_L_ORIGINE;
	}

	public void setEMPRUNTS_A_PLUS_D_1_AN_A_L_ORIGINE(int eMPRUNTS_A_PLUS_D_1_AN_A_L_ORIGINE) {
		EMPRUNTS_A_PLUS_D_1_AN_A_L_ORIGINE = eMPRUNTS_A_PLUS_D_1_AN_A_L_ORIGINE;
	}

	public int getEMPRUNTS_ET_DETTES_FINANCIERES_DIVERS() {
		return EMPRUNTS_ET_DETTES_FINANCIERES_DIVERS;
	}

	public void setEMPRUNTS_ET_DETTES_FINANCIERES_DIVERS(int eMPRUNTS_ET_DETTES_FINANCIERES_DIVERS) {
		EMPRUNTS_ET_DETTES_FINANCIERES_DIVERS = eMPRUNTS_ET_DETTES_FINANCIERES_DIVERS;
	}

	public int getFOURNISSEURS_ET_COMPTES_RATTACHES() {
		return FOURNISSEURS_ET_COMPTES_RATTACHES;
	}

	public void setFOURNISSEURS_ET_COMPTES_RATTACHES(int fOURNISSEURS_ET_COMPTES_RATTACHES) {
		FOURNISSEURS_ET_COMPTES_RATTACHES = fOURNISSEURS_ET_COMPTES_RATTACHES;
	}

	public int getSECURITE_SOCIALE_ET_AUTRES_ORGANISMES_SOCIAUX() {
		return SECURITE_SOCIALE_ET_AUTRES_ORGANISMES_SOCIAUX;
	}

	public void setSECURITE_SOCIALE_ET_AUTRES_ORGANISMES_SOCIAUX(int sECURITE_SOCIALE_ET_AUTRES_ORGANISMES_SOCIAUX) {
		SECURITE_SOCIALE_ET_AUTRES_ORGANISMES_SOCIAUX = sECURITE_SOCIALE_ET_AUTRES_ORGANISMES_SOCIAUX;
	}

	public int getTVA() {
		return TVA;
	}

	public void setTVA(int tVA) {
		TVA = tVA;
	}

	public int getOBLIGATIONS_CAUTIONNEES() {
		return OBLIGATIONS_CAUTIONNEES;
	}

	public void setOBLIGATIONS_CAUTIONNEES(int oBLIGATIONS_CAUTIONNEES) {
		OBLIGATIONS_CAUTIONNEES = oBLIGATIONS_CAUTIONNEES;
	}

	public int getAUTRES_IMPOTS_TAXES_ET_ASSIMILES() {
		return AUTRES_IMPOTS_TAXES_ET_ASSIMILES;
	}

	public void setAUTRES_IMPOTS_TAXES_ET_ASSIMILES(int aUTRES_IMPOTS_TAXES_ET_ASSIMILES) {
		AUTRES_IMPOTS_TAXES_ET_ASSIMILES = aUTRES_IMPOTS_TAXES_ET_ASSIMILES;
	}

	public int getAUTRES_DETTES_DONT_DETTES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRE() {
		return AUTRES_DETTES_DONT_DETTES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRE;
	}

	public void setAUTRES_DETTES_DONT_DETTES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRE(
			int aUTRES_DETTES_DONT_DETTES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRE) {
		AUTRES_DETTES_DONT_DETTES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRE = aUTRES_DETTES_DONT_DETTES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRE;
	}

	public int getDETTE_REPRESENTATIVE_DE_TITRES_EMPRUNTES() {
		return DETTE_REPRESENTATIVE_DE_TITRES_EMPRUNTES;
	}

	public void setDETTE_REPRESENTATIVE_DE_TITRES_EMPRUNTES(int dETTE_REPRESENTATIVE_DE_TITRES_EMPRUNTES) {
		DETTE_REPRESENTATIVE_DE_TITRES_EMPRUNTES = dETTE_REPRESENTATIVE_DE_TITRES_EMPRUNTES;
	}

	public int getPRODUITS_CONSTATES_D_AVANCE() {
		return PRODUITS_CONSTATES_D_AVANCE;
	}

	public void setPRODUITS_CONSTATES_D_AVANCE(int pRODUITS_CONSTATES_D_AVANCE) {
		PRODUITS_CONSTATES_D_AVANCE = pRODUITS_CONSTATES_D_AVANCE;
	}

	public int getTOTAL_ETAT_DES_DETTES() {
		return TOTAL_ETAT_DES_DETTES;
	}

	public void setTOTAL_ETAT_DES_DETTES(int tOTAL_ETAT_DES_DETTES) {
		TOTAL_ETAT_DES_DETTES = tOTAL_ETAT_DES_DETTES;
	}

	public int getEMPRUNTS_SOUSCRITS_EN_COURS_D_EXERCICE() {
		return EMPRUNTS_SOUSCRITS_EN_COURS_D_EXERCICE;
	}

	public void setEMPRUNTS_SOUSCRITS_EN_COURS_D_EXERCICE(int eMPRUNTS_SOUSCRITS_EN_COURS_D_EXERCICE) {
		EMPRUNTS_SOUSCRITS_EN_COURS_D_EXERCICE = eMPRUNTS_SOUSCRITS_EN_COURS_D_EXERCICE;
	}

	public int getEMPRUNTS_REMBOURSES_EN_COURS_D_EXERCICE() {
		return EMPRUNTS_REMBOURSES_EN_COURS_D_EXERCICE;
	}

	public void setEMPRUNTS_REMBOURSES_EN_COURS_D_EXERCICE(int eMPRUNTS_REMBOURSES_EN_COURS_D_EXERCICE) {
		EMPRUNTS_REMBOURSES_EN_COURS_D_EXERCICE = eMPRUNTS_REMBOURSES_EN_COURS_D_EXERCICE;
	}

	public int getAFFECTATION_DU_RESULTAT_RENSEIGNEMENTS_DIVERS() {
		return AFFECTATION_DU_RESULTAT_RENSEIGNEMENTS_DIVERS;
	}

	public void setAFFECTATION_DU_RESULTAT_RENSEIGNEMENTS_DIVERS(int aFFECTATION_DU_RESULTAT_RENSEIGNEMENTS_DIVERS) {
		AFFECTATION_DU_RESULTAT_RENSEIGNEMENTS_DIVERS = aFFECTATION_DU_RESULTAT_RENSEIGNEMENTS_DIVERS;
	}

	public int getDIVIDENDES() {
		return DIVIDENDES;
	}

	public void setDIVIDENDES(int dIVIDENDES) {
		DIVIDENDES = dIVIDENDES;
	}

	public int getENGAGEMENT_DE_CREDITBAIL_MOBILIER() {
		return ENGAGEMENT_DE_CREDITBAIL_MOBILIER;
	}

	public void setENGAGEMENT_DE_CREDITBAIL_MOBILIER(int eNGAGEMENT_DE_CREDITBAIL_MOBILIER) {
		ENGAGEMENT_DE_CREDITBAIL_MOBILIER = eNGAGEMENT_DE_CREDITBAIL_MOBILIER;
	}

	public int getENGAGEMENT_DE_CREDITBAIL_IMMOBILIER() {
		return ENGAGEMENT_DE_CREDITBAIL_IMMOBILIER;
	}

	public void setENGAGEMENT_DE_CREDITBAIL_IMMOBILIER(int eNGAGEMENT_DE_CREDITBAIL_IMMOBILIER) {
		ENGAGEMENT_DE_CREDITBAIL_IMMOBILIER = eNGAGEMENT_DE_CREDITBAIL_IMMOBILIER;
	}

	public int getEFFETS_PORTES_A_L_ESCOMPTE_ET_NON_ECHUS() {
		return EFFETS_PORTES_A_L_ESCOMPTE_ET_NON_ECHUS;
	}

	public void setEFFETS_PORTES_A_L_ESCOMPTE_ET_NON_ECHUS(int eFFETS_PORTES_A_L_ESCOMPTE_ET_NON_ECHUS) {
		EFFETS_PORTES_A_L_ESCOMPTE_ET_NON_ECHUS = eFFETS_PORTES_A_L_ESCOMPTE_ET_NON_ECHUS;
	}

	public int getSOUSTRAITANCE() {
		return SOUSTRAITANCE;
	}

	public void setSOUSTRAITANCE(int sOUSTRAITANCE) {
		SOUSTRAITANCE = sOUSTRAITANCE;
	}

	public int getLOCATION_CHARGES_LOCATIVES_ET_DE_COPROPRIETE() {
		return LOCATION_CHARGES_LOCATIVES_ET_DE_COPROPRIETE;
	}

	public void setLOCATION_CHARGES_LOCATIVES_ET_DE_COPROPRIETE(int lOCATION_CHARGES_LOCATIVES_ET_DE_COPROPRIETE) {
		LOCATION_CHARGES_LOCATIVES_ET_DE_COPROPRIETE = lOCATION_CHARGES_LOCATIVES_ET_DE_COPROPRIETE;
	}

	public int getPERSONNEL_EXTERIEUR_A_L_ENTREPRISE() {
		return PERSONNEL_EXTERIEUR_A_L_ENTREPRISE;
	}

	public void setPERSONNEL_EXTERIEUR_A_L_ENTREPRISE(int pERSONNEL_EXTERIEUR_A_L_ENTREPRISE) {
		PERSONNEL_EXTERIEUR_A_L_ENTREPRISE = pERSONNEL_EXTERIEUR_A_L_ENTREPRISE;
	}

	public int getREMUNERATION_D_INTERMEDIAIRES_ET_HONORAIRES_HORS_RETROCESSIONS() {
		return REMUNERATION_D_INTERMEDIAIRES_ET_HONORAIRES_HORS_RETROCESSIONS;
	}

	public void setREMUNERATION_D_INTERMEDIAIRES_ET_HONORAIRES_HORS_RETROCESSIONS(
			int rEMUNERATION_D_INTERMEDIAIRES_ET_HONORAIRES_HORS_RETROCESSIONS) {
		REMUNERATION_D_INTERMEDIAIRES_ET_HONORAIRES_HORS_RETROCESSIONS = rEMUNERATION_D_INTERMEDIAIRES_ET_HONORAIRES_HORS_RETROCESSIONS;
	}

	public int getRETROCESSIONS_D_HONORAIRES_COMMISSIONS_ET_COURTAGES() {
		return RETROCESSIONS_D_HONORAIRES_COMMISSIONS_ET_COURTAGES;
	}

	public void setRETROCESSIONS_D_HONORAIRES_COMMISSIONS_ET_COURTAGES(
			int rETROCESSIONS_D_HONORAIRES_COMMISSIONS_ET_COURTAGES) {
		RETROCESSIONS_D_HONORAIRES_COMMISSIONS_ET_COURTAGES = rETROCESSIONS_D_HONORAIRES_COMMISSIONS_ET_COURTAGES;
	}

	public int getAUTRES_COMPTES() {
		return AUTRES_COMPTES;
	}

	public void setAUTRES_COMPTES(int aUTRES_COMPTES) {
		AUTRES_COMPTES = aUTRES_COMPTES;
	}

	public int getTOTAL_DU_POSTE_CORRESPONDANT_A_LA_LIGNE_FW_DU_TABLEAU_NUMERO_2052() {
		return TOTAL_DU_POSTE_CORRESPONDANT_A_LA_LIGNE_FW_DU_TABLEAU_NUMERO_2052;
	}

	public void setTOTAL_DU_POSTE_CORRESPONDANT_A_LA_LIGNE_FW_DU_TABLEAU_NUMERO_2052(
			int tOTAL_DU_POSTE_CORRESPONDANT_A_LA_LIGNE_FW_DU_TABLEAU_NUMERO_2052) {
		TOTAL_DU_POSTE_CORRESPONDANT_A_LA_LIGNE_FW_DU_TABLEAU_NUMERO_2052 = tOTAL_DU_POSTE_CORRESPONDANT_A_LA_LIGNE_FW_DU_TABLEAU_NUMERO_2052;
	}

	public int getTAXE_PROFESSIONNELLE() {
		return TAXE_PROFESSIONNELLE;
	}

	public void setTAXE_PROFESSIONNELLE(int tAXE_PROFESSIONNELLE) {
		TAXE_PROFESSIONNELLE = tAXE_PROFESSIONNELLE;
	}

	public int getAUTRES_IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES() {
		return AUTRES_IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES;
	}

	public void setAUTRES_IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES(int aUTRES_IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES) {
		AUTRES_IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES = aUTRES_IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES;
	}

	public int getTOTAL_DU_COMPTE_CORRESPONDANT_A_LA_LIGNE_FX_DU_TABLEAU_NUMERO_2052() {
		return TOTAL_DU_COMPTE_CORRESPONDANT_A_LA_LIGNE_FX_DU_TABLEAU_NUMERO_2052;
	}

	public void setTOTAL_DU_COMPTE_CORRESPONDANT_A_LA_LIGNE_FX_DU_TABLEAU_NUMERO_2052(
			int tOTAL_DU_COMPTE_CORRESPONDANT_A_LA_LIGNE_FX_DU_TABLEAU_NUMERO_2052) {
		TOTAL_DU_COMPTE_CORRESPONDANT_A_LA_LIGNE_FX_DU_TABLEAU_NUMERO_2052 = tOTAL_DU_COMPTE_CORRESPONDANT_A_LA_LIGNE_FX_DU_TABLEAU_NUMERO_2052;
	}

	public int getMONTANT_DE_LA_TVA_COLLECTEE() {
		return MONTANT_DE_LA_TVA_COLLECTEE;
	}

	public void setMONTANT_DE_LA_TVA_COLLECTEE(int mONTANT_DE_LA_TVA_COLLECTEE) {
		MONTANT_DE_LA_TVA_COLLECTEE = mONTANT_DE_LA_TVA_COLLECTEE;
	}

	public int getTOTAL_TVA_DEDUCTIBLE_SUR_BIENS_ET_SERVICES() {
		return TOTAL_TVA_DEDUCTIBLE_SUR_BIENS_ET_SERVICES;
	}

	public void setTOTAL_TVA_DEDUCTIBLE_SUR_BIENS_ET_SERVICES(int tOTAL_TVA_DEDUCTIBLE_SUR_BIENS_ET_SERVICES) {
		TOTAL_TVA_DEDUCTIBLE_SUR_BIENS_ET_SERVICES = tOTAL_TVA_DEDUCTIBLE_SUR_BIENS_ET_SERVICES;
	}

	public int getEFFECTIF_MOYEN_DU_PERSONNEL() {
		return EFFECTIF_MOYEN_DU_PERSONNEL;
	}

	public void setEFFECTIF_MOYEN_DU_PERSONNEL(int eFFECTIF_MOYEN_DU_PERSONNEL) {
		EFFECTIF_MOYEN_DU_PERSONNEL = eFFECTIF_MOYEN_DU_PERSONNEL;
	}

	public int getFILIALES_ET_PARTICIPATIONS() {
		return FILIALES_ET_PARTICIPATIONS;
	}

	public void setFILIALES_ET_PARTICIPATIONS(int fILIALES_ET_PARTICIPATIONS) {
		FILIALES_ET_PARTICIPATIONS = fILIALES_ET_PARTICIPATIONS;
	}
  
	
	
	
}
